import Link from 'next/link';
import { ArrowRight, CircleAlert, FileText, LockKeyhole, ReceiptText } from 'lucide-react';
import type { FinanceInvoice } from '@/lib/finance/types';
import { formatFinanceMoney, monthOfDate } from '@/lib/finance/reports';
import styles from './finance.module.css';
import {OrderVariantDetails} from '@/components/commerce/order-variant-details';

function amount(value: number | null) { return value === null ? 'غير مكتمل' : formatFinanceMoney(value); }
function date(value: string) { return new Intl.DateTimeFormat('ar-SA', { dateStyle: 'long', timeStyle: 'short', calendar: 'gregory', timeZone: 'Asia/Riyadh' }).format(new Date(value)); }
const documentLabels = { invoice: 'فاتورة', credit_note: 'إشعار دائن', debit_note: 'إشعار مدين' };

export function FinanceInvoiceView({ invoice, internal, printHref, canExport = true }: { invoice: FinanceInvoice; internal: boolean; printHref?: string; canExport?: boolean }) {
  const snapshot = invoice.snapshot;
  const vatOff = snapshot?.version === 2 && snapshot.vatControl?.enabled === false;
  const cancelled = invoice.status === 'cancelled';
  const pending = !cancelled && (invoice.status === 'pending_policy' || !snapshot);
  const archive = `/admin/finance?section=invoices&month=${monthOfDate(invoice.at)}&mode=accountant`;
  const sourceOrder = internal ? `/admin/commerce/orders/${encodeURIComponent(invoice.orderId)}` : `/account/orders/${encodeURIComponent(invoice.orderId)}`;
  return <article className={styles.invoice} dir="rtl"><div className={`${styles.row} ${styles.noPrint}`}><Link href={internal ? archive : sourceOrder} className={styles.textLink}><ArrowRight size={14} style={{ display: 'inline' }} aria-hidden="true" /> {internal ? 'أرشيف الفواتير' : 'العودة للطلب'}</Link><div className={styles.actions}>{internal && <Link href={`/admin/finance/invoices/${encodeURIComponent(invoice.id)}?view=customer`} className={styles.secondaryButton}>معاينة نسخة العميل</Link>}{canExport && <a href={printHref || `/admin/finance/export?format=print&invoiceId=${encodeURIComponent(invoice.id)}${internal ? '' : '&view=customer'}`} className={styles.secondaryButton} target="_blank" rel="noreferrer"><FileText size={16} aria-hidden="true" /> طباعة / حفظ PDF</a>}</div></div>
    {cancelled && <div className={styles.notice} style={{marginTop:18}} role="status"><CircleAlert size={20} aria-hidden="true"/><div><strong>مسودة ملغاة — ليست فاتورة صادرة.</strong><p>يبقى سجل الطلب محفوظًا للمراجعة. لا تُستخدم هذه المسودة كمستند ضريبي أو مطالبة مالية.</p></div></div>}
    {pending && <div className={styles.notice} style={{ marginTop: 18 }} role="status"><CircleAlert size={20} aria-hidden="true" /><div><strong>سجل مالي بانتظار اعتماد سياسة الإصدار — ليس فاتورة ضريبية مُصدرة.</strong><p>القيمة والطلب محفوظان من مصدر العملية. بيانات جهة الإصدار والضريبة لم تُعتمد؛ لا يُستنتج مبلغ الضريبة أو نسبتها من الإجمالي. النسخة المطبوعة لا تثبت الامتثال للفوترة الإلكترونية.</p></div></div>}
    <div className={styles.invoicePaper}>{vatOff && <p className={styles.notice}>ضريبة القيمة المضافة غير مضافة على هذا المستند.</p>}<header className={styles.invoiceHeader}><div><span className={styles.brand}><span className={styles.brandMark}><ReceiptText size={16} aria-hidden="true" /></span> تربح</span><h1 className={styles.title}>{cancelled ? 'مسودة ملغاة' : pending ? 'سجل عملية بيع' : documentLabels[invoice.kind]}</h1><p className={styles.muted}>{internal ? 'نسخة الإدارة · تتضمن مراجع داخلية' : 'نسخة العميل'}</p></div><div><span className={`${styles.badge} ${pending ? styles.badgeWarning : styles.badgeGood}`}>{cancelled ? 'ملغى' : pending ? 'بانتظار السياسة' : 'مُصدر'}</span><p><strong>{invoice.number || `سجل #${invoice.id}`}</strong></p><p className={styles.muted}>{pending || cancelled ? 'تاريخ حفظ السجل' : 'تاريخ الإصدار'}: {date(invoice.issuedAt || invoice.at)}</p><p className={styles.muted}>العملة: الريال السعودي (SAR)</p></div></header>
      <div className={styles.invoiceParties}><section><h2 className={styles.sectionTitle}>جهة الإصدار</h2>{snapshot ? <><p>{snapshot.issuer.name}</p><p className={styles.muted}>{snapshot.issuer.address}</p>{!vatOff && <p className={styles.muted}>الرقم الضريبي: <bdi>{snapshot.issuer.taxNumber}</bdi></p>}</> : <p className={styles.muted}>بانتظار اعتماد جهة الإصدار وبياناتها.</p>}</section><section><h2 className={styles.sectionTitle}>بيانات العميل</h2><p>{snapshot?.customer.name || invoice.source.customerName}</p>{snapshot?.customer.address && <p className={styles.muted}>{snapshot.customer.address}</p>}<p className={styles.muted}>رقم الطلب: <Link href={sourceOrder} className={styles.textLink}>#{invoice.orderId}</Link></p>{invoice.parentId && <p className={styles.muted}>المستند الأصلي: {internal ? <Link className={styles.textLink} href={`/admin/finance/invoices/${encodeURIComponent(invoice.parentId)}`}>#{invoice.parentId}</Link> : `#${invoice.parentId}`}</p>}</section></div>
      <div className={styles.tableWrap}><table className={styles.table}><caption>{snapshot ? 'بنود المستند المحفوظة وقت الإصدار' : 'بنود الطلب المحفوظة — التفصيل الضريبي غير معتمد'}</caption><thead><tr><th>الوصف والخيارات</th><th>الكمية</th><th>{snapshot?.version===1 ? 'سعر الوحدة قبل الضريبة' : 'سعر الوحدة المسجل'}</th>{snapshot ? <><th>الخصم</th><th>{vatOff ? 'القيمة الصافية' : 'الوعاء الضريبي'}</th><th>نسبة الضريبة</th><th>الضريبة</th></> : <th>الخصم</th>}<th>{snapshot ? (vatOff ? 'الإجمالي' : 'الإجمالي شامل الضريبة') : 'إجمالي البند المسجل'}</th></tr></thead><tbody>{snapshot ? snapshot.lines.map(line => <tr key={line.key}><td>{line.title}{'variantSnapshot' in line&&<OrderVariantDetails value={line.variantSnapshot}/>}</td><td>{line.quantity}</td><td className={styles.money}>{amount('unitPriceMinor' in line?line.unitPriceMinor:line.unitNetMinor)}{!vatOff && 'priceBasis' in line&&<small className={styles.muted}> {line.priceBasis==='inclusive'?'شامل الضريبة':'قبل الضريبة'}</small>}</td><td className={styles.money}>{amount(line.discountMinor)}</td><td className={styles.money}>{amount(line.netMinor)}</td><td>{(line.vatBps / 100).toFixed(2)}%</td><td className={styles.money}>{amount(line.vatMinor)}</td><td className={styles.money}>{amount(line.grossMinor)}</td></tr>) : invoice.source.items.map((item, index) => <tr key={`${item.productId}-${index}`}><td>{item.title}<OrderVariantDetails value={item.variantSnapshot}/></td><td>{item.quantity}</td><td className={styles.money}>{amount(item.listUnitMinor??item.unitMinor)}</td><td className={styles.money}>{amount(item.discountMinor??0)}</td><td className={styles.money}>{amount(item.totalMinor)}</td></tr>)}</tbody></table></div>
      <div className={styles.invoiceTotals}><div className={styles.row}><span>{vatOff ? 'القيمة الصافية' : 'القيمة قبل الضريبة'}</span><strong className={styles.money}>{amount(snapshot?.netMinor ?? invoice.netMinor)}</strong></div><div className={styles.row}><span>الضريبة</span><strong className={styles.money}>{amount(snapshot?.vatMinor ?? invoice.vatMinor)}</strong></div>{!snapshot && <div className={styles.row}><span>الشحن المسجل ضمن إجمالي الطلب</span><span className={styles.money}>{amount(invoice.source.shippingMinor)}</span></div>}<div className={`${styles.row} ${styles.invoiceTotal}`}><span>{pending ? 'الإجمالي المسجل' : 'إجمالي المستند'}</span><strong className={styles.money}>{amount(snapshot?.totalMinor ?? invoice.totalMinor)}</strong></div>{snapshot && <><div className={styles.row}><span>المبلغ المدفوع</span><span className={styles.money}>{amount(snapshot.paidMinor)}</span></div><div className={styles.row}><span>المتبقي</span><span className={styles.money}>{amount(snapshot.totalMinor - snapshot.paidMinor)}</span></div></>}</div>
      {invoice.reason && <p className={styles.muted} style={{ marginTop: 20 }}>ملاحظة المستند: {invoice.reason}</p>}
      {!pending && !cancelled && <div className={styles.success} style={{ marginTop: 20 }}><LockKeyhole size={17} aria-hidden="true" /><p>المستند محفوظ بقيمه وقت الإصدار. أي تصحيح مالي لاحق يكون بمستند مستقل مرتبط بالأصل.</p></div>}
      <footer className={styles.footer}><span>تربح · مرجع الطلب #{invoice.orderId}</span><span>البيانات المنظمة المحفوظة هي مرجع المراجعة؛ الطباعة وحدها ليست اعتمادًا ضريبيًا.</span></footer>
    </div>
    {internal && <section className={`${styles.panel} ${styles.panelPad}`} style={{ marginTop: 18 }} aria-label="تفاصيل الإدارة الداخلية"><div className={styles.sectionHeading}><div><h2 className={styles.sectionTitle}>مراجع الإدارة الداخلية</h2><p className={styles.sectionDescription}>هذه التفاصيل مستبعدة من نسخة العميل.</p></div><FileText size={20} aria-hidden="true" /></div><div className={styles.formGrid}><div><p className={styles.muted}>مرجع المقبوض</p><p className={styles.break}>#{invoice.receiptId}</p></div><div><p className={styles.muted}>مرجع السياسة</p><p>{snapshot?.policyReference || 'غير معتمد'}</p></div></div><div className={styles.tableWrap}><table className={styles.table}><caption>قيمة المورد المحفوظة في مصدر الطلب</caption><thead><tr><th>المورد</th><th>المنتج المرجعي</th><th>قيمة المورد</th><th>كشف الحساب</th></tr></thead><tbody>{invoice.source.suppliers.map((supplier, index) => <tr key={`${supplier.supplierId}-${supplier.productId}-${index}`}><td>{supplier.supplierName}</td><td>#{supplier.productId}</td><td className={styles.money}>{amount(supplier.amountMinor)}</td><td><Link className={styles.textLink} href={`/admin/finance?section=suppliers&month=${monthOfDate(invoice.at)}&mode=accountant&supplierId=${encodeURIComponent(supplier.supplierId)}`}>فتح كشف المورد</Link></td></tr>)}</tbody></table></div><div className={styles.actions} style={{ marginTop: 15 }}><Link className={styles.textLink} href={sourceOrder}>تفاصيل الطلب</Link><Link className={styles.textLink} href={`/admin/finance?section=reconciliation&month=${monthOfDate(invoice.at)}&q=${encodeURIComponent(invoice.orderId)}`}>المطابقة</Link><Link className={styles.textLink} href={`/admin/finance?section=ledger&mode=accountant&month=${monthOfDate(invoice.at)}&q=${encodeURIComponent(invoice.id)}`}>سجل التدقيق</Link></div></section>}
  </article>;
}
