import { createHash } from 'node:crypto';
import Link from 'next/link';
import { ArrowLeft, ArrowUpLeft, BookOpen, CalendarDays, CheckCircle2, CircleAlert, Download, FileClock, FileText, Layers3, LockKeyhole, ReceiptText, Scale, Search, ShieldCheck, SlidersHorizontal, Store, TrendingUp, Wallet } from 'lucide-react';
import type { FinanceInvoice, FinanceMetric, FinanceQuery, FinanceReport, FinanceSection, FinanceSupplier } from '@/lib/finance/types';
import { budgetLabels, formatFinanceMoney, monthOfDate, settlementCandidates } from '@/lib/finance/reports';
import { approveFinanceSettlement, captureFinanceInvoices, closeFinanceMonth, prepareFinanceSettlement, recordFinanceExpense, releaseFinanceAccrual, reverseFinanceExpense, reverseFinanceSettlement, saveFinanceBudget } from '@/app/admin/finance/actions';
import { FinanceSubmitButton } from './finance-controls';
import styles from './finance.module.css';

export type FinanceWorkspaceProps = { report: FinanceReport; canEdit: boolean; canApprove: boolean; canClose: boolean; canExport: boolean; actionKey: string };
type Context = FinanceWorkspaceProps & { writable: boolean };
const sections: { key: FinanceSection; label: string; icon: typeof Wallet; accountant?: boolean }[] = [
  { key: 'overview', label: 'نظرة عامة', icon: Layers3 }, { key: 'suppliers', label: 'حسابات الموردين', icon: Store },
  { key: 'settlements', label: 'التسويات', icon: ArrowUpLeft }, { key: 'budget', label: 'ميزانية الشهر', icon: SlidersHorizontal },
  { key: 'month-end', label: 'ملخص الشهر', icon: CalendarDays }, { key: 'cashflow', label: 'التدفق النقدي', icon: TrendingUp },
  { key: 'expenses', label: 'المصروفات', icon: Wallet }, { key: 'invoices', label: 'أرشيف الفواتير', icon: ReceiptText },
  { key: 'reconciliation', label: 'المطابقة', icon: Scale }, { key: 'close', label: 'إقفال الشهر', icon: LockKeyhole },
  { key: 'tax', label: 'مراجعة الضريبة', icon: ShieldCheck, accountant: true }, { key: 'ledger', label: 'الحركات والتدقيق', icon: BookOpen, accountant: true },
];
const statusLabels: Record<string, string> = { held: 'معلّق للمراجعة', not_due: 'لم يحن موعده', due: 'مستحق الآن', overdue: 'متأخر', partial: 'مدفوع جزئيًا', paid: 'مدفوع بالكامل', draft: 'بانتظار الاعتماد', approved: 'تحويل موثق', reversed: 'حركة معكوسة', pending_policy: 'بانتظار السياسة', issued: 'مُصدر', invoice: 'فاتورة', credit_note: 'إشعار دائن', debit_note: 'إشعار مدين', awaiting_payment: 'بانتظار الدفع', payment_review: 'مراجعة الدفع', cancelled: 'ملغى', opening: 'رصيد افتتاحي', adjustment: 'تعديل بمستند مستقل' };
const dateFormatter = new Intl.DateTimeFormat('ar-SA', { day: 'numeric', month: 'short', year: 'numeric', calendar: 'gregory', timeZone: 'Asia/Riyadh' });
const auditLabels: Record<string, string> = { budget_saved: 'تحديث الميزانية', expense_recorded: 'تسجيل مصروف', expense_reversed: 'عكس مصروف', accrual_released: 'إجازة استحقاق', settlement_prepared: 'تجهيز تسوية', settlement_approved: 'توثيق تحويل خارجي', settlement_reversed: 'عكس تسوية', invoice_captured: 'حفظ سجل فاتورة', invoice_issued: 'إصدار مستند', month_closed: 'إقفال الشهر', report_exported: 'تصدير تقرير', invoice_exported: 'تصدير فاتورة', credit_note_issued: 'إصدار إشعار دائن', debit_note_issued: 'إصدار إشعار مدين', refund_recorded: 'توثيق استرداد نقدي' };
const entityLabels: Record<string, string> = { budget: 'ميزانية', expense: 'مصروف', accrual: 'استحقاق', settlement: 'تسوية', invoice: 'مستند فاتورة', period: 'فترة', report: 'تقرير', refund: 'استرداد' };
export function financeDate(value: string | null): string { return value && Number.isFinite(Date.parse(value)) ? dateFormatter.format(new Date(value)) : 'غير محدد'; }
function monthTitle(month: string) { return new Intl.DateTimeFormat('ar-SA', { month: 'long', year: 'numeric', calendar: 'gregory', timeZone: 'Asia/Riyadh' }).format(new Date(`${month}-01T12:00:00Z`)); }
function money(value: number | null) { return value === null ? 'غير مكتمل' : formatFinanceMoney(value).replace(/ ر\.س$/, ''); }
function href(query: FinanceQuery, updates: Partial<FinanceQuery> = {}, extra?: Record<string, string>) {
  const target = { ...query, ...updates };
  const params = new URLSearchParams({ section: target.section, month: target.month, mode: target.mode });
  if (target.supplierId) params.set('supplierId', target.supplierId);
  if (target.q) params.set('q', target.q);
  if (target.status) params.set('status', target.status);
  Object.entries(extra || {}).forEach(([key, value]) => params.set(key, value));
  return `/admin/finance?${params}`;
}
function sectionHref(query: FinanceQuery, section: FinanceSection) { return href(query, { section, q: undefined, status: undefined }); }
function orderHref(id: string) { return `/admin/commerce/orders/${encodeURIComponent(id)}`; }
function invoiceHref(id: string) { return `/admin/finance/invoices/${encodeURIComponent(id)}`; }
function formKey(key: string, purpose: string) {
  const hex = createHash('sha256').update(`${key}:${purpose}`).digest('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(13, 16)}-a${hex.slice(17, 20)}-${hex.slice(20, 32)}`;
}
function Fields({ context, purpose }: { context: Context; purpose: string }) {
  return <><input type="hidden" name="requestKey" value={formKey(context.actionKey, purpose)} /><input type="hidden" name="month" value={context.report.query.month} /><input type="hidden" name="returnTo" value={context.report.query.section} /></>;
}
function Badge({ status }: { status: string }) {
  const tone = ['paid', 'approved', 'issued'].includes(status) ? styles.badgeGood : ['overdue', 'reversed'].includes(status) ? styles.badgeError : ['held', 'draft', 'pending_policy', 'partial'].includes(status) ? styles.badgeWarning : '';
  return <span className={`${styles.badge} ${tone}`}>{statusLabels[status] || status}</span>;
}
function Empty({ title, children }: { title: string; children: React.ReactNode }) { return <div className={styles.empty}><span className={styles.emptyIcon}><FileClock size={23} aria-hidden="true" /></span><strong>{title}</strong><p>{children}</p></div>; }
function Panel({ title, description, children, action, pad = true }: { title: string; description?: string; children: React.ReactNode; action?: React.ReactNode; pad?: boolean }) {
  return <section className={`${styles.panel} ${pad ? styles.panelPad : ''}`}><div className={`${styles.sectionHeading} ${!pad ? styles.panelPad : ''}`}><div><h2 className={styles.sectionTitle}>{title}</h2>{description && <p className={styles.sectionDescription}>{description}</p>}</div>{action}</div>{children}</section>;
}
function Metric({ metric, previous }: { metric: FinanceMetric; previous?: FinanceMetric }) {
  return <article className={styles.metric}><div className={styles.metricLabel}><span>{metric.label}</span><ArrowUpLeft size={14} aria-hidden="true" /></div><Link href={metric.href} className={`${styles.metricValue} ${styles.money}`}>{money(metric.valueMinor)}{metric.valueMinor !== null && <small className={styles.muted}> ر.س</small>}</Link>{previous && <p className={styles.muted}>الشهر السابق: {money(previous.valueMinor)}{previous.valueMinor !== null ? ' ر.س' : ''}</p>}<details className={styles.metricHelp}><summary>ما معنى هذا الرقم؟</summary><p>{metric.explanation}</p><Link href={metric.href} className={styles.textLink}>عرض المصدر</Link></details></article>;
}
function MetricGrid({ report, keys, previous = false }: { report: FinanceReport; keys?: string[]; previous?: boolean }) {
  const metrics = keys ? keys.map(key => report.metrics.find(item => item.key === key)).filter((item): item is FinanceMetric => Boolean(item)) : report.metrics;
  return <div className={styles.metrics}>{metrics.map(metric => <Metric key={metric.key} metric={metric} previous={previous ? report.previousMetrics.find(item => item.key === metric.key) : undefined} />)}</div>;
}
function Issues({ report, all = false }: { report: FinanceReport; all?: boolean }) {
  const issues = all ? report.issues : report.issues.slice(0, 5);
  if (!issues.length) return <div className={styles.success}><CheckCircle2 size={18} aria-hidden="true" /><span>لم تظهر فروقات في فحوص المصادر المتاحة. تبقى مراجعة السياسة والمستندات ضمن خطوات الإقفال.</span></div>;
  return <div>{issues.map(issue => <Link href={issue.href} key={issue.key} className={styles.issue}><span className={styles.issueIcon}><CircleAlert size={15} aria-hidden="true" /></span><span className={styles.issueBody}><strong>{issue.message}</strong>{issue.differenceMinor !== undefined && <span className={styles.muted}> · الفرق: {money(issue.differenceMinor)} ر.س</span>}</span><ArrowLeft size={15} aria-hidden="true" /></Link>)}</div>;
}
function PeriodFilters({ query, suppliers }: { query: FinanceQuery; suppliers: FinanceSupplier[] }) {
  return <form action="/admin/finance" method="get" className={`${styles.toolbar} ${styles.noPrint}`}><input type="hidden" name="section" value={query.section} /><input type="hidden" name="mode" value={query.mode} />
    <label className={`${styles.field} ${styles.filterField}`}>الفترة<input className={styles.input} type="month" name="month" required defaultValue={query.month} /></label>
    <label className={`${styles.field} ${styles.filterField}`}>المورد<select name="supplierId" className={styles.select} defaultValue={query.supplierId || ''}><option value="">جميع الموردين</option>{suppliers.map(supplier => <option value={supplier.id} key={supplier.id}>{supplier.name}</option>)}</select></label>
    <label className={`${styles.field} ${styles.searchField}`}>البحث في السجلات<input className={styles.input} type="search" name="q" defaultValue={query.q || ''} placeholder="رقم طلب، فاتورة، عميل أو مرجع…" /></label>
    {['invoices', 'settlements', 'suppliers', 'ledger'].includes(query.section) && <label className={`${styles.field} ${styles.filterField}`}>الحالة<select name="status" className={styles.select} defaultValue={query.status || ''}><option value="">كل الحالات</option>{(query.section === 'invoices' ? ['pending_policy', 'issued'] : query.section === 'settlements' ? ['draft', 'approved', 'reversed'] : ['held', 'not_due', 'due', 'overdue', 'partial', 'paid', 'draft', 'reversed', 'adjustment']).map(status => <option value={status} key={status}>{statusLabels[status]}</option>)}</select></label>}
    <button className={`${styles.button} ${styles.filterSubmit}`}><Search size={15} aria-hidden="true" /> عرض</button>
    {(query.q || query.status || query.supplierId) && <Link className={`${styles.textLink} ${styles.filterSubmit}`} href={href(query, { q: undefined, status: undefined, supplierId: undefined })}>مسح التصفية</Link>}
  </form>;
}
function matchesQuery(query: FinanceQuery, ...values: (string | number | null)[]) { return !query.q || values.filter(value => value !== null).join(' ').toLocaleLowerCase('ar').includes(query.q.toLocaleLowerCase('ar')); }
function invoiceMatches(invoice: FinanceInvoice, query: FinanceQuery) { return monthOfDate(invoice.at) === query.month && (!query.supplierId || invoice.source.suppliers.some(supplier => supplier.supplierId === query.supplierId)) && (!query.status || invoice.status === query.status) && matchesQuery(query, invoice.id, invoice.number, invoice.orderId, invoice.at, financeDate(invoice.at), invoice.source.customerName, invoice.totalMinor / 100, invoice.source.suppliers.map(supplier => supplier.supplierName).join(' ')); }
function SourceReceipts({ report }: { report: FinanceReport }) {
  const { data, query } = report;
  const receipts = data.receipts.filter(receipt => monthOfDate(receipt.at) === query.month && (!query.supplierId || data.orders.find(order => order.id === receipt.orderId)?.suppliers.some(supplier => supplier.supplierId === query.supplierId)) && matchesQuery(query, receipt.reference, receipt.id, receipt.orderId));
  return <Panel title="المقبوضات الموثقة" description="كل مبلغ مرتبط بمرجع الدفع والطلب الذي أنشأه." pad={false}>{!receipts.length ? <Empty title="لا توجد مقبوضات مطابقة">غيّر الفترة أو التصفية. تظهر هنا المقبوضات الموثقة للسلع المعتمدة.</Empty> : <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>الطلب</th><th>تاريخ التحصيل</th><th>مرجع الدفع</th><th>المحصل</th><th>مستند الفاتورة</th></tr></thead><tbody>{receipts.map(receipt => { const invoice = data.invoices.find(item => item.receiptId === receipt.id); return <tr key={receipt.id}><td><Link className={styles.textLink} href={orderHref(receipt.orderId)}>#{receipt.orderId}</Link></td><td>{financeDate(receipt.at)}</td><td className={styles.break}>{receipt.reference || 'غير متاح'}</td><td className={styles.money}>{money(receipt.amountMinor)} ر.س</td><td>{invoice ? <Link className={styles.textLink} href={invoiceHref(invoice.id)}>{invoice.number || 'عرض السجل المعلق'}</Link> : <span className={styles.badgeWarning}>مستند ناقص</span>}</td></tr>; })}</tbody></table></div>}</Panel>;
}
function SourceRefunds({ report }: { report: FinanceReport }) {
  const { data, query } = report;
  const refunds = data.refunds.filter(refund => monthOfDate(refund.at) === query.month && (!query.supplierId || data.orders.find(order => order.id === refund.orderId)?.suppliers.some(supplier => supplier.supplierId === query.supplierId)) && matchesQuery(query, refund.id, refund.orderId, refund.externalId, refund.evidenceRef));
  return <Panel title="الاستردادات النقدية الموثقة" description="حركات مؤكدة بمراجعها الخارجية؛ إشعار الفاتورة وحده لا يثبت رد المال." pad={false}>{refunds.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>الطلب</th><th>تاريخ الاسترداد</th><th>المزوّد والمرجع</th><th>المبلغ المسترد</th><th>دليل التوثيق</th></tr></thead><tbody>{refunds.map(refund => <tr key={refund.id}><td><Link href={orderHref(refund.orderId)} className={styles.textLink}>#{refund.orderId}</Link><p className={styles.muted}>المقبوض #{refund.receiptId}</p></td><td>{financeDate(refund.at)}</td><td className={styles.break}>{refund.provider}<p className={styles.muted}>{refund.externalId}</p></td><td className={styles.money}>{money(refund.amountMinor)} ر.س</td><td className={styles.break}>{refund.evidenceRef}</td></tr>)}</tbody></table></div> : <Empty title="لا توجد حركات استرداد موثقة مطابقة">تظهر الحركات عند وصول دليل الاسترداد من المصدر المعتمد. لا يُنفذ استرداد مالي من هذه الشاشة.</Empty>}</Panel>;
}
function Overview({ context }: { context: Context }) {
  const { report } = context;
  const collected = report.metrics.find(metric => metric.key === 'collected');
  return <div className={styles.stack}><div><section className={styles.hero}><div><p className={styles.heroLabel}>المبالغ المحصلة · {monthTitle(report.query.month)}</p><p className={styles.heroValue}>{money(collected?.valueMinor ?? null)} <small className={styles.heroLabel}>ر.س</small></p><p className={styles.heroNote}>نظرة يومية على دخل التجارة ومصروفاتها والتزاماتها.</p></div><div className={styles.heroSide}><Link href={sectionHref(report.query, 'cashflow')} className={styles.heroLink}><span>التزامات معروفة خلال 7 أيام</span><strong>{money(report.due7Minor)} <small className={styles.small}>ر.س</small></strong></Link><Link href={sectionHref(report.query, 'suppliers')} className={styles.heroLink}><span>حسابات الموردين</span><strong>{report.suppliers.length} <small className={styles.small}>مورد</small></strong></Link><Link href={sectionHref(report.query, 'reconciliation')} className={styles.heroLink}><span>بنود تحتاج متابعة</span><strong>{report.issues.length} <small className={styles.small}>بند</small></strong></Link></div></section><MetricGrid report={report} keys={['sales', 'supplier_cost', 'supplier_paid', 'supplier_remaining', 'trbhh_income', 'operating_expenses', 'payment_fees', 'shipping', 'refunds', 'vat', 'net_income', 'cashflow']} /></div>
    <div className={styles.grid}><Panel title="ما يحتاج انتباهك" description="تنبيهات مرتبطة بالمصدر لتسهيل المراجعة." action={<Link href={sectionHref(report.query, 'reconciliation')} className={styles.textLink}>كل البنود</Link>}><Issues report={report} /></Panel><Panel title="خطواتك اليومية" description="من متابعة التحصيل إلى توثيق المصروف والتحويل."><div className={styles.stack}>{[{ title: 'راجع حسابات الموردين', text: 'المستحق والمعلّق وآخر تسوية لكل مورد.', section: 'suppliers' as const, icon: Store }, { title: 'وثّق مصروفًا', text: 'المبلغ والضريبة المسجلة والمستند المرجعي.', section: 'expenses' as const, icon: Wallet }, { title: 'راجع أرشيف الفواتير', text: 'نفس السجل المالي وروابطه ومصدره.', section: 'invoices' as const, icon: ReceiptText }].map(item => <Link key={item.section} href={sectionHref(report.query, item.section)} className={styles.row}><span className={styles.issueIcon}><item.icon size={16} aria-hidden="true" /></span><span style={{ flex: 1 }}><strong className={styles.small}>{item.title}</strong><p className={styles.muted}>{item.text}</p></span><ArrowLeft size={16} aria-hidden="true" /></Link>)}</div></Panel></div><SourceReceipts report={report} /><SourceRefunds report={report} /></div>;
}
function Statement({ report }: { report: FinanceReport }) {
  const rows = report.movements.filter(row => (!report.query.status || row.status === report.query.status) && matchesQuery(report.query, row.id, row.label, row.orderId, row.reference));
  return <Panel title={report.query.supplierId ? 'كشف حساب المورد' : 'حركات حسابات الموردين'} description="الرصيد تراكمي حسب ترتيب الحركات، والتصفية لا تعيد احتساب الأرصدة." pad={false}>{rows.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>التاريخ</th><th>الحركة / المصدر</th><th>له</th><th>عليه / مسدد</th><th>الرصيد</th><th>الحالة</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{financeDate(row.at)}</td><td><Link className={styles.textLink} href={row.href}>{row.label}</Link><p className={`${styles.muted} ${styles.break}`}>{row.reference || (row.orderId ? `طلب #${row.orderId}` : row.id)}</p></td><td className={styles.money}>{money(row.creditMinor)} ر.س</td><td className={styles.money}>{money(row.debitMinor)} ر.س</td><td className={styles.money}><strong>{money(row.balanceMinor)} ر.س</strong></td><td><Badge status={row.status} /></td></tr>)}</tbody></table></div> : <Empty title="لا توجد حركات مطابقة">عند تسجيل استحقاق أو تسوية، تظهر الحركة هنا مع مرجعها وحالتها.</Empty>}</Panel>;
}
function AccrualReview({ context }: { context: Context }) {
  const { report } = context;
  const rows = report.data.accruals.filter(row => !row.eligibleAt && monthOfDate(row.at) <= report.query.month && (!report.query.supplierId || row.supplierId === report.query.supplierId) && matchesQuery(report.query, row.id, row.orderId, row.holdReason));
  return <Panel title="استحقاقات معلّقة للمراجعة" description="لا يصبح المبلغ مستحقًا بمجرد الدفع؛ وثّق استيفاء شروط المورد أولًا.">{rows.length ? <div className={styles.stack}>{rows.map(row => <details key={row.id} className={styles.details}><summary>طلب #{row.orderId} · {report.data.suppliers.find(supplier => supplier.id === row.supplierId)?.name || row.supplierId} · {money(row.amountMinor)} ر.س</summary><p className={styles.muted}>{row.holdReason || 'شروط التسوية تحتاج مراجعة واعتمادًا.'} <Link href={orderHref(row.orderId)} className={styles.textLink}>مراجعة الطلب</Link></p>{context.canApprove && context.writable && monthOfDate(new Date()) === report.query.month && <form action={releaseFinanceAccrual} className={styles.form}><Fields context={context} purpose={`release-${row.id}`} /><input type="hidden" name="accrualId" value={row.id} /><label className={styles.field}>تاريخ الاستحقاق بعد المراجعة<input type="date" name="dueAt" className={styles.input} required /></label><label className={styles.field}>مرجع اعتماد الشروط وسبب الإجازة<textarea name="reason" className={styles.textarea} minLength={3} maxLength={1000} required placeholder="اذكر الاتفاق أو مستند إثبات اكتمال الشروط" /></label><FinanceSubmitButton className={styles.button}>توثيق إجازة الاستحقاق</FinanceSubmitButton></form>}</details>)}</div> : <Empty title="لا توجد استحقاقات معلّقة مطابقة">تظهر هنا المبالغ التي تحتاج إثبات استيفاء شروط التسوية.</Empty>}</Panel>;
}
function Suppliers({ context }: { context: Context }) {
  const { report } = context;
  const suppliers = report.suppliers.filter(supplier => (!report.query.supplierId || supplier.id === report.query.supplierId) && matchesQuery(report.query, supplier.id, supplier.name));
  return <div className={styles.stack}><Panel title="كل مورد، وحسابه واضح" description="المتبقي يشمل المستحق والمعلّق. صافي الالتزام لا يعني أنه متاح للتحويل الآن." pad={false}>{suppliers.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>المورد</th><th>افتتاحي</th><th>قيمة الطلبات</th><th>المسدد</th><th>معلّق</th><th>المتبقي له</th><th>مستحق الآن</th><th>آخر تسوية</th></tr></thead><tbody>{suppliers.map(supplier => <tr key={supplier.id}><td><Link className={styles.textLink} href={href(report.query, { supplierId: supplier.id, q: undefined, status: undefined })}>{supplier.name}</Link><p className={styles.muted}>{supplier.overdueMinor > 0 ? <span className={styles.negative}>متأخر: {money(supplier.overdueMinor)} ر.س</span> : supplier.nextDueAt ? `الاستحقاق القادم: ${financeDate(supplier.nextDueAt)}` : 'موعد الاستحقاق غير محدد'}</p></td><td className={styles.money}>{money(supplier.openingMinor)}</td><td className={styles.money}>{money(supplier.accruedMinor)}</td><td className={styles.money}>{money(supplier.paidMinor)}</td><td className={styles.money}>{money(supplier.pendingMinor)}</td><td className={styles.money}><strong>{money(supplier.remainingMinor)}</strong></td><td className={styles.money}>{money(supplier.dueMinor)}</td><td>{financeDate(supplier.lastSettlementAt)}</td></tr>)}</tbody></table></div> : <Empty title="لا توجد حسابات موردين مطابقة">أزل التصفية أو راجع ربط الموردين بالطلبات المعتمدة.</Empty>}</Panel><Statement report={report} /><AccrualReview context={context} /></div>;
}
function Settlements({ context }: { context: Context }) {
  const { report } = context;
  const rows = report.data.settlements.filter(row => monthOfDate(row.at) === report.query.month && (!report.query.supplierId || row.supplierId === report.query.supplierId) && (!report.query.status || row.status === report.query.status) && matchesQuery(report.query, row.id, row.reference, row.reason, report.data.suppliers.find(supplier => supplier.id === row.supplierId)?.name || ''));
  const eligible = report.query.supplierId ? settlementCandidates(report.data, report.query.supplierId) : [];
  const currentMonth = monthOfDate(new Date()) === report.query.month;
  return <div className={styles.stack}><div className={styles.notice}><CircleAlert size={18} aria-hidden="true" /><p>هذه الشاشة توثّق تحويلًا تم خارج تربح. تجهيز المسودة أو اعتمادها لا يحوّل أموالًا ولا يتصل بالبنك. اعتماد التحويل وعكسه متاحان في الشهر الحالي فقط.</p></div>
    {context.canEdit && <Panel title="تجهيز تسوية للمراجعة" description="اختر المورد من التصفية، ثم الطلبات المجازة والمستحقة. ستراجع المسودة قبل اعتمادها.">{!report.query.supplierId ? <Empty title="اختر موردًا لبدء التسوية">استخدم حقل المورد أعلى الصفحة لعرض المبالغ المؤهلة وتجهيز مسودة مستقلة.</Empty> : eligible.length ? <form action={prepareFinanceSettlement} className={styles.form}><Fields context={context} purpose="prepare-settlement" /><input type="hidden" name="supplierId" value={report.query.supplierId} /><fieldset className={styles.stack}><legend className={styles.small}>الطلبات المقترحة للتسوية</legend>{eligible.map(({ accrual: row, remainingMinor }) => <label key={row.id} className={styles.checkbox}><input name="accrualIds" value={row.id} type="checkbox" /><span>طلب <Link href={orderHref(row.orderId)} className={styles.textLink}>#{row.orderId}</Link> · {money(remainingMinor)} ر.س <span className={styles.muted}>· مستحق {financeDate(row.dueAt)}</span></span></label>)}</fieldset><label className={styles.field}>سبب التسوية ومرجع المراجعة<textarea name="reason" className={styles.textarea} minLength={3} maxLength={1000} required /></label><div className={styles.formFooter}><span className={styles.muted}>إعداد مسودة فقط؛ لا يعتبر المبلغ مسددًا.</span><FinanceSubmitButton className={styles.button} disabled={!context.writable || !currentMonth}>إنشاء مسودة ومعاينة</FinanceSubmitButton></div></form> : <Empty title="لا توجد مبالغ مؤهلة جديدة لهذا المورد">قد تكون المبالغ معلّقة، لم يحن موعدها، أو مدرجة بالفعل في تسوية. راجع كشف المورد.</Empty>}</Panel>}
    <Panel title="التسويات المسجلة" description="المسودة لا تخفض المستحق. المرجع الخارجي والتأكيد مطلوبان للاعتماد.">{rows.length ? <div className={styles.stack}>{rows.map(row => { const supplier = report.data.suppliers.find(item => item.id === row.supplierId); const balance = report.suppliers.find(item => item.id === row.supplierId); return <article key={row.id} id={`settlement-${row.id}`} className={styles.details}><div className={styles.sectionHeading}><div><h3 className={styles.sectionTitle}>{supplier?.name || `مورد #${row.supplierId}`}</h3><p className={styles.muted}>تسوية #{row.id} · {financeDate(row.at)}</p></div><Badge status={row.reversalOf ? 'reversed' : row.status} /></div><div className={styles.row}><span className={styles.muted}>{row.reversalOf ? `حركة عكسية للتسوية #${row.reversalOf}` : 'المبلغ النهائي للتسوية'}</span><strong className={styles.metricValue}>{money(row.reversalOf ? -row.amountMinor : row.amountMinor)} <small className={styles.muted}>ر.س</small></strong></div>{row.status === 'draft' && balance && <p className={styles.muted}>الرصيد الافتتاحي للمورد في التقرير: {money(balance.openingMinor)} ر.س · المتبقي المسجل: {money(balance.remainingMinor)} ر.س</p>}<p className={styles.small}>{row.reason}</p>{row.reference && <p className={`${styles.muted} ${styles.break}`}>مرجع التحويل الخارجي: {row.reference}</p>}<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>الطلب / الاستحقاق</th><th>القيمة</th></tr></thead><tbody>{row.lines.map(line => { const accrual = report.data.accruals.find(item => item.id === line.accrualId); return <tr key={line.accrualId}><td>{accrual ? <Link href={orderHref(accrual.orderId)} className={styles.textLink}>طلب #{accrual.orderId}</Link> : `استحقاق #${line.accrualId}`}</td><td className={styles.money}>{money(line.amountMinor)} ر.س</td></tr>; })}</tbody></table></div>
      {row.status === 'draft' && <div className={styles.notice}><FileText size={17} aria-hidden="true" /><span>هذه معاينة لمسودة. تعتمد على الاستحقاقات المختارة دون افتراض مرتجعات أو خصومات غير مسجلة. راجع الاتفاق والمستندات قبل توثيق التحويل.</span></div>}
      {row.status === 'draft' && context.canApprove && <form action={approveFinanceSettlement} className={styles.form}><Fields context={context} purpose={`approve-${row.id}`} /><input type="hidden" name="settlementId" value={row.id} /><label className={styles.field}>مرجع التحويل المنفذ خارج النظام<input name="reference" className={styles.input} required minLength={3} maxLength={200} /></label><label className={styles.checkbox}><input type="checkbox" name="confirm" value="1" required /><span>راجعت البنود وأؤكد أن التحويل تم خارج النظام وأن المرجع صحيح.</span></label><FinanceSubmitButton className={styles.button} disabled={!context.writable || !currentMonth}>اعتماد وتوثيق التحويل</FinanceSubmitButton></form>}
      {row.status === 'approved' && !row.reversalOf && context.canApprove && <details className={styles.details}><summary>تصحيح التسوية بحركة عكسية</summary><form action={reverseFinanceSettlement} className={styles.form}><Fields context={context} purpose={`reverse-settlement-${row.id}`} /><input type="hidden" name="settlementId" value={row.id} /><label className={styles.field}>سبب التصحيح ومستنده<textarea name="reason" className={styles.textarea} required minLength={3} maxLength={1000} /></label><p className={styles.muted}>يبقى السجل الأصلي محفوظًا. تسجل حركة مقابلة في الفترة الحالية، ولا ينفذ هذا الإجراء استردادًا بنكيًا.</p><FinanceSubmitButton className={styles.dangerButton} disabled={!context.writable || !currentMonth}>تسجيل حركة عكسية</FinanceSubmitButton></form></details>}
    </article>; })}</div> : <Empty title="لا توجد تسويات في الفترة المختارة">تبدأ التسوية بمسودة للمراجعة، ثم تعتمد بمرجع التحويل المنفذ.</Empty>}</Panel></div>;
}
function Budget({ context }: { context: Context }) {
  const { report } = context;
  return <div className={styles.stack}><Panel title="المخطط مقابل الفعلي" description="الأرقام بالريال السعودي. النسبة والفرق غير متاحين عندما يكون المصدر الفعلي ناقصًا." pad={false}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>البند</th><th>المخطط</th><th>الفعلي</th><th>الفرق</th><th>نسبة الفعلي إلى المخطط</th></tr></thead><tbody>{report.budget.map(row => <tr key={row.category}><td><Link className={styles.textLink} href={sectionHref(report.query, ['sales', 'trbhh_income', 'supplier_cost', 'tax', 'refunds'].includes(row.category) ? row.category === 'tax' ? 'tax' : 'reconciliation' : 'expenses')}>{row.label}</Link></td><td className={styles.money}>{money(row.plannedMinor)}</td><td className={styles.money}>{money(row.actualMinor)}</td><td className={styles.money}>{money(row.differenceMinor)}</td><td style={{ minWidth: 150 }}>{row.usagePercent === null ? <span className={styles.muted}>غير متاح</span> : <><strong className={row.usagePercent > 100 ? styles.negative : ''}>{row.usagePercent.toFixed(1)}%</strong><div className={`${styles.progress} ${row.usagePercent > 100 ? styles.progressOver : ''}`}><span style={{ width: `${Math.min(100, Math.max(0, row.usagePercent))}%` }} /></div></>}</td></tr>)}</tbody></table></div></Panel>
    {context.canEdit && <Panel title="تحديث بند في ميزانية الشهر" description="يُحفظ المخطط للشهر المختار دون تغيير الحركات الفعلية."><form action={saveFinanceBudget} className={styles.form}><Fields context={context} purpose="budget" /><div className={styles.formGrid}><label className={styles.field}>بند الميزانية<select name="category" className={styles.select} required>{Object.entries(budgetLabels).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label className={styles.field}>المبلغ المخطط (ر.س)<input type="number" name="planned" className={styles.input} inputMode="decimal" step="0.01" min="0" required placeholder="0.00" /></label></div><div className={styles.formFooter}><span className={styles.muted}>الفترة: {monthTitle(report.query.month)}</span><FinanceSubmitButton className={styles.button} disabled={!context.writable}>حفظ المخطط</FinanceSubmitButton></div></form></Panel>}</div>;
}
function Expenses({ context }: { context: Context }) {
  const { report } = context;
  const rows = report.data.expenses.filter(row => monthOfDate(row.at) === report.query.month && matchesQuery(report.query, row.id, row.description, row.reference, budgetLabels[row.category]));
  const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Riyadh', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
  const occurredAt = today.startsWith(report.query.month) ? today : '';
  const lastDay = new Date(`${report.query.month}-01T12:00:00Z`); lastDay.setUTCMonth(lastDay.getUTCMonth() + 1); lastDay.setUTCDate(0);
  const categories = Object.entries(budgetLabels).filter(([key]) => !['sales', 'trbhh_income', 'supplier_cost', 'refunds', 'tax'].includes(key));
  return <div className={styles.stack}>{report.query.supplierId && <div className={styles.notice}><CircleAlert size={18} aria-hidden="true" /><p>مصروفات التشغيل تخص المنصة ولا تنسب تلقائيًا إلى المورد المختار. القائمة أدناه تعرض مصروفات الفترة كاملة.</p></div>}
    {context.canEdit && <Panel title="تسجيل مصروف" description="أدخل القيم كما تظهر في المستند. الضريبة المدخلة ليست اعتمادًا لقابليتها للخصم."><form action={recordFinanceExpense} className={styles.form}><Fields context={context} purpose="expense" /><div className={styles.formGrid}><label className={styles.field}>التصنيف<select name="category" className={styles.select} required>{categories.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className={styles.field}>تاريخ المصروف<input type="date" name="occurredAt" className={styles.input} required defaultValue={occurredAt} min={`${report.query.month}-01`} max={lastDay.toISOString().slice(0, 10)} /></label><label className={`${styles.field} ${styles.wide}`}>وصف المصروف<input name="description" className={styles.input} required maxLength={500} placeholder="مثال: اشتراك استضافة شهر سبتمبر" /></label><label className={styles.field}>القيمة قبل الضريبة (ر.س)<input name="net" type="number" inputMode="decimal" step="0.01" min="0" className={styles.input} required /></label><label className={styles.field}>الضريبة في المستند (ر.س)<input name="vat" type="number" inputMode="decimal" step="0.01" min="0" className={styles.input} required placeholder="اكتب 0 فقط إن كانت صفرًا في المستند" /></label><label className={styles.field}>المبلغ المدفوع فعليًا (ر.س)<input name="paid" type="number" inputMode="decimal" step="0.01" min="0" className={styles.input} required /></label><label className={styles.field}>تاريخ استحقاق المتبقي<input name="dueAt" type="date" className={styles.input} required defaultValue={occurredAt} /></label><label className={`${styles.field} ${styles.wide}`}>مرجع الفاتورة أو المستند<input name="reference" className={styles.input} required maxLength={200} /></label></div><div className={styles.formFooter}><span className={styles.muted}>راجع القيم قبل الحفظ؛ التصحيح يتم بحركة عكسية.</span><FinanceSubmitButton className={styles.button} disabled={!context.writable}>تسجيل المصروف</FinanceSubmitButton></div></form></Panel>}
    <Panel title="المصروفات المسجلة" description="المبالغ التاريخية محفوظة. التصحيح يظهر بحركة مستقلة." pad={false}>{rows.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>المصروف</th><th>التاريخ</th><th>قبل الضريبة</th><th>ضريبة المستند</th><th>الإجمالي</th><th>المدفوع</th><th>المراجعة</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} id={`expense-${row.id}`}><td><strong>{row.description}</strong><p className={styles.muted}>{budgetLabels[row.category]} · {row.reference}</p>{row.reversalOf && <Badge status="reversed" />}</td><td>{financeDate(row.at)}<p className={styles.muted}>الاستحقاق: {financeDate(row.dueAt)}</p></td><td className={styles.money}>{money(row.reversalOf ? -row.netMinor : row.netMinor)}</td><td className={styles.money}>{money(row.reversalOf ? -row.vatMinor : row.vatMinor)}</td><td className={styles.money}>{money(row.reversalOf ? -row.totalMinor : row.totalMinor)}</td><td className={styles.money}>{money(row.reversalOf ? -row.paidMinor : row.paidMinor)}</td><td>{!row.reversalOf && !report.data.expenses.some(item => item.reversalOf === row.id) && context.canApprove ? <details><summary className={styles.textLink}>تسجيل تصحيح</summary><form action={reverseFinanceExpense} className={styles.form}><Fields context={context} purpose={`reverse-expense-${row.id}`} /><input type="hidden" name="expenseId" value={row.id} /><label className={styles.field}>سبب الحركة العكسية<textarea name="reason" required minLength={3} maxLength={1000} className={styles.textarea} /></label><FinanceSubmitButton className={styles.dangerButton} disabled={!context.writable || monthOfDate(new Date()) !== report.query.month}>عكس المصروف</FinanceSubmitButton></form></details> : <span className={styles.muted}>سجل محفوظ</span>}</td></tr>)}</tbody></table></div> : <Empty title="لا توجد مصروفات مطابقة">أضف المصروف من مستنده لتظهر قيمته في الميزانية والتدفق النقدي.</Empty>}</Panel></div>;
}
function InvoiceArchive({ context }: { context: Context }) {
  const { report } = context;
  const invoices = report.data.invoices.filter(invoice => invoiceMatches(invoice, report.query));
  return <div className={styles.stack}><div className={styles.notice}><ReceiptText size={18} aria-hidden="true" /><p>السجل المعلّق يحفظ مرجع العملية وقيمتها. لا يصبح فاتورة ضريبية مُصدرة حتى اعتماد جهة الإصدار والسياسة والتكامل المطلوب. الطباعة وحدها لا تثبت الامتثال للفوترة الإلكترونية.</p></div>
    {context.canEdit && <form action={captureFinanceInvoices} className={`${styles.row} ${styles.panel} ${styles.panelPad}`}><Fields context={context} purpose="capture-invoices" /><div><strong className={styles.small}>مراجعة اكتمال الأرشيف</strong><p className={styles.muted}>إنشاء السجلات المعلّقة الناقصة للمقبوضات الموثقة دون تكرار السجلات الموجودة أو إصدار ضريبي.</p></div><FinanceSubmitButton className={styles.secondaryButton} disabled={!context.writable}>حفظ السجلات الناقصة</FinanceSubmitButton></form>}
    <Panel title="أرشيف الفواتير" description={`${invoices.length} مستند مطابق · ${monthTitle(report.query.month)}`} pad={false}>{invoices.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>المستند</th><th>الطلب والعميل</th><th>التاريخ</th><th>قبل الضريبة</th><th>الضريبة</th><th>الإجمالي</th><th>الحالة</th></tr></thead><tbody>{invoices.map(invoice => <tr key={invoice.id}><td><Link className={styles.textLink} href={invoiceHref(invoice.id)}>{invoice.number || `سجل #${invoice.id}`}</Link><p className={styles.muted}>{statusLabels[invoice.kind]}</p></td><td><Link className={styles.textLink} href={orderHref(invoice.orderId)}>#{invoice.orderId}</Link><p className={styles.muted}>{invoice.source.customerName}</p></td><td>{financeDate(invoice.at)}</td><td className={styles.money}>{money(invoice.netMinor)}</td><td className={styles.money}>{money(invoice.vatMinor)}</td><td className={styles.money}><strong>{money(invoice.totalMinor)} ر.س</strong></td><td><Badge status={invoice.status} /></td></tr>)}</tbody></table></div> : <Empty title="لا توجد فواتير مطابقة">ابحث برقم الفاتورة أو الطلب أو العميل، أو غيّر الشهر والحالة.</Empty>}</Panel></div>;
}
function Cashflow({ report }: { report: FinanceReport }) {
  return <div className={styles.stack}><div className={styles.notice}><Wallet size={18} aria-hidden="true" /><p>التدفق أدناه مبني على الحركات المسجلة فقط. رصيد الحساب البنكي والضريبة المستحقة غير المكتملة لا يُفترضان من هذه الأرقام.</p></div><MetricGrid report={report} keys={['collected', 'supplier_paid', 'operating_expenses', 'cashflow']} /><div className={styles.grid}><Panel title="الالتزامات القادمة" description="المبالغ ذات مواعيد الاستحقاق المعروفة في الموردين والمصروفات."><div className={styles.stack}><Link href={sectionHref(report.query, 'suppliers')} className={styles.row}><span>خلال 7 أيام</span><strong className={styles.money}>{money(report.due7Minor)} ر.س</strong></Link><Link href={sectionHref(report.query, 'suppliers')} className={styles.row}><span>خلال 30 يومًا</span><strong className={styles.money}>{money(report.due30Minor)} ر.س</strong></Link><div className={styles.row}><span>المتبقي من النقد المسجل بعد الالتزامات المعروفة</span><Link href={sectionHref(report.query, 'reconciliation')} className={`${styles.textLink} ${styles.money}`}>{money(report.availableMinor)} ر.س</Link></div></div></Panel><Panel title="قبل اتخاذ قرار بالصرف" description="استكمل المصادر التي قد تغيّر السيولة المتاحة."><Issues report={report} /><Link href={sectionHref(report.query, 'expenses')} className={styles.textLink}>مراجعة المصروفات ومواعيدها</Link></Panel></div><SourceReceipts report={report} /><SourceRefunds report={report} /></div>;
}
function MonthEnd({ report }: { report: FinanceReport }) {
  return <div className={styles.stack}><Panel title={`حكاية الشهر بالأرقام · ${monthTitle(report.query.month)}`} description="نفس مصادر اللوحة اليومية، مع مقارنة الفترة السابقة. لا تعني المبالغ المحصلة صافي ربح."><p className={styles.small}>راجع المبيعات والتحصيل وما دفع للموردين وما بقي لهم، ثم المصروفات والضريبة. كل قيمة تفتح مصدرها، والقيم غير المكتملة تحتاج اعتمادًا قبل الحكم على نتيجة الشهر.</p></Panel><MetricGrid report={report} previous /><div className={styles.grid}><Panel title="المتبقي بعد الالتزامات المعروفة"><Link href={sectionHref(report.query, 'cashflow')} className={styles.metricValue}>{money(report.availableMinor)} <small className={styles.muted}>ر.س</small></Link><p className={styles.muted}>مؤشر من الحركات المسجلة، ولا يمثل رصيد البنك أو سيولة نهائية قبل اكتمال الالتزامات.</p></Panel><Panel title="جاهزية مراجعة الشهر"><Issues report={report} /><Link href={sectionHref(report.query, 'close')} className={styles.button}>متابعة خطوات الإقفال <ArrowLeft size={15} aria-hidden="true" /></Link></Panel></div></div>;
}
const closeSteps: { key: string; title: string; description: string; section: FinanceSection }[] = [
  { key: 'payment', title: 'مطابقة المدفوعات', description: 'راجع كل مقبوض ومرجعه والمبلغ المتوقع للطلب.', section: 'reconciliation' },
  { key: 'refunds', title: 'مراجعة المرتجعات', description: 'أكّد اكتمال سجلات المرتجعات والاسترداد والسياسة المعتمدة.', section: 'reconciliation' },
  { key: 'suppliers', title: 'مراجعة حسابات الموردين', description: 'راجع المعلّق والمستحق والتسويات ومراجع التحويل.', section: 'suppliers' },
  { key: 'invoices', title: 'فحص الفواتير والضريبة', description: 'تحقق من المستندات الثابتة وجهة الإصدار والسياسة الضريبية.', section: 'invoices' },
  { key: 'expenses', title: 'استكمال المصروفات', description: 'سجل المستندات الناقصة وتحقق من المبالغ المدفوعة.', section: 'expenses' },
  { key: 'differences', title: 'مراجعة الفروقات', description: 'راجع كل فرق ابتداء من هللة، دون تسويات صامتة.', section: 'reconciliation' },
  { key: 'review', title: 'المراجعة النهائية', description: 'راجع ملخص الشهر ومرجعه واعتمد اكتمال الأدلة.', section: 'month-end' },
];
function CloseMonth({ context }: { context: Context }) {
  const { report } = context;
  const period = report.data.periods.find(item => item.month === report.query.month);
  return <div className={styles.grid}><Panel title="إقفال الشهر، خطوة بخطوة" description={monthTitle(report.query.month)}>{period?.closedAt ? <div className={styles.success}><LockKeyhole size={19} aria-hidden="true" /><div><strong>الشهر مقفل منذ {financeDate(period.closedAt)}</strong><p>{period.reason}</p></div></div> : <form action={closeFinanceMonth} className={styles.form}><Fields context={context} purpose="close-month" /><fieldset disabled={!context.canClose || !context.writable}><legend className={styles.muted}>أكمل المراجعة ثم علّم على كل خطوة.</legend>{closeSteps.map((step, index) => <div key={step.key} className={styles.checkStep}><span className={styles.stepNumber}>{index + 1}</span><div className={styles.stepBody}><label className={styles.checkbox}><input type="checkbox" name="checks" value={step.key} required /><span><strong>{step.title}</strong><span className={styles.muted}>{step.description}</span></span></label><Link href={sectionHref(report.query, step.section)} className={styles.textLink}>فتح المصدر</Link></div></div>)}</fieldset><label className={styles.field}>ملاحظة الاعتماد ومرجع المراجعة<textarea name="reason" className={styles.textarea} required minLength={3} maxLength={1000} disabled={!context.canClose || !context.writable} /></label><FinanceSubmitButton className={styles.button} disabled={!context.canClose || !context.writable || !report.canClose}>اعتماد إقفال {monthTitle(report.query.month)}</FinanceSubmitButton><p className={styles.muted}>يعاد فحص البيانات عند الاعتماد. بعد الإقفال تُمنع الكتابة بأثر رجعي في هذا الشهر.</p></form>}</Panel><Panel title="ما يمنع الإقفال" description="تحديد الخطوات لا يتجاوز الفحوص المالية أو نقص السياسة."><Issues report={report} all />{!report.canClose && <p className={styles.notice}>الإقفال غير متاح حتى معالجة البنود المانعة واستكمال المصادر المطلوبة.</p>}{!context.canClose && <p className={styles.muted}>صلاحيتك تسمح بالمراجعة؛ اعتماد الإقفال يتطلب صلاحية مستقلة.</p>}</Panel></div>;
}
function Reconciliation({ report }: { report: FinanceReport }) {
  const orders = report.data.orders.filter(order => monthOfDate(order.paidAt || order.createdAt) === report.query.month && (!report.query.supplierId || order.suppliers.some(supplier => supplier.supplierId === report.query.supplierId)) && matchesQuery(report.query, order.id, order.customerName));
  return <div className={styles.stack}><Panel title="مطابقة يمكن تتبعها" description="مقارنة الطلبات بالمقبوضات والاستحقاقات والفواتير. تظهر الفروقات ابتداء من هللة واحدة."><Issues report={report} all /></Panel><Panel title="مصادر الطلبات" description="افتح الطلب أو مستند الفاتورة لفهم القيم التي كوّنت التقرير." pad={false}>{orders.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>الطلب</th><th>العميل</th><th>حالة الطلب</th><th>إجمالي الطلب</th><th>الشحن المسجل</th><th>المقبوضات</th><th>الفواتير</th></tr></thead><tbody>{orders.map(order => <tr key={order.id} id={`order-${order.id}`}><td><Link className={styles.textLink} href={orderHref(order.id)}>#{order.id}</Link><p className={styles.muted}>{financeDate(order.paidAt || order.createdAt)}</p></td><td>{order.customerName}</td><td><Badge status={order.status} /></td><td className={styles.money}>{money(order.totalMinor)} ر.س</td><td className={styles.money}>{money(order.shippingMinor)} ر.س</td><td>{report.data.receipts.filter(receipt => receipt.orderId === order.id).map(receipt => <p key={receipt.id} className={styles.small}>{money(receipt.amountMinor)} ر.س <span className={`${styles.muted} ${styles.break}`}>· {receipt.reference}</span></p>)}</td><td>{report.data.invoices.filter(invoice => invoice.orderId === order.id).map(invoice => <p key={invoice.id}><Link className={styles.textLink} href={invoiceHref(invoice.id)}>{invoice.number || `سجل #${invoice.id}`}</Link> <Badge status={invoice.status} /></p>)}</td></tr>)}</tbody></table></div> : <Empty title="لا توجد طلبات مطابقة">تظهر هنا طلبات السلع المعتمدة ومصادرها المالية في الفترة المحددة.</Empty>}</Panel><SourceReceipts report={report} /><SourceRefunds report={report} /></div>;
}
function TaxReview({ report }: { report: FinanceReport }) {
  const invoices = report.data.invoices.filter(invoice => invoiceMatches(invoice, { ...report.query, status: undefined }));
  const pending = invoices.filter(invoice => invoice.status === 'pending_policy');
  const taxIssues = report.issues.filter(issue => /tax|vat|invoice|policy|refund/i.test(issue.key));
  return <div className={styles.stack}><div className={styles.notice}><ShieldCheck size={19} aria-hidden="true" /><p>هذه قائمة تجهيز ومراجعة داخلية، وليست إقرارًا ضريبيًا أو إثباتًا للامتثال. الإصدار الرسمي يتطلب سياسة معتمدة ومتطلبات الفوترة الإلكترونية ذات الصلة.</p></div><MetricGrid report={report} keys={['vat', 'refunds', 'net_income']} /><div className={styles.grid}><Panel title="قائمة ما قبل الإقرار" description="اجمع الأدلة والمستندات قبل تقديم التقرير للمختص.">{[{ title: 'جهة الإصدار والمعالجة الضريبية', text: 'تحتاج اعتمادًا صريحًا؛ لا تستنتج النسبة من سعر الطلب.' }, { title: 'اكتمال مستندات الفترة', text: `${invoices.length} مستند مطابق، منها ${pending.length} سجل بانتظار السياسة.` }, { title: 'المرتجعات والإشعارات', text: 'راجع مصادر الاسترداد وربط أي إشعار بالمستند الأصلي.' }, { title: 'ضريبة المصروفات', text: 'طابق القيم مع المستندات وراجع أهلية الخصم مع المختص.' }, { title: 'سجل التدقيق والتصدير', text: 'احتفظ بالسجلات المنظمة والمراجع، إلى جانب النسخة المطبوعة.' }].map((item, index) => <div key={item.title} className={styles.checkStep}><span className={styles.stepNumber}>{index + 1}</span><div className={styles.stepBody}><strong>{item.title}</strong><p className={styles.muted}>{item.text}</p></div></div>)}</Panel><Panel title="بنود تحتاج مراجعة ضريبية"><Issues report={{ ...report, issues: taxIssues }} all /><Link className={styles.button} href={sectionHref(report.query, 'invoices')}>فتح أرشيف الفواتير <ArrowLeft size={16} aria-hidden="true" /></Link></Panel></div></div>;
}
function Ledger({ report }: { report: FinanceReport }) {
  const audit = report.data.audit.filter(row => monthOfDate(row.at) === report.query.month && matchesQuery(report.query, row.id, row.actorId, row.action, row.entityId, row.reason));
  return <div className={styles.stack}><div className={styles.notice}><BookOpen size={18} aria-hidden="true" /><p>هذه حركات المصادر وسجل التدقيق الداخلي. دفتر الأستاذ العام الكامل يحتاج دليل حسابات وسياسة ترحيل معتمدين؛ لا تُنشأ قيود يدوية من هذه الشاشة.</p></div><Statement report={report} /><SourceReceipts report={report} /><SourceRefunds report={report} /><Panel title="سجل التدقيق" description="من قام بالإجراء، ومتى، وعلى أي مستند، ولماذا." pad={false}>{audit.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>التاريخ</th><th>المستخدم</th><th>الإجراء</th><th>المستند</th><th>السبب</th></tr></thead><tbody>{audit.map(row => <tr key={row.id}><td>{financeDate(row.at)}</td><td>#{row.actorId}</td><td>{auditLabels[row.action] || row.action}</td><td className={styles.break}>{entityLabels[row.entity] || row.entity} #{row.entityId}</td><td>{row.reason || '—'}</td></tr>)}</tbody></table></div> : <Empty title="لا توجد أحداث تدقيق مطابقة">تظهر هنا عمليات التسجيل والاعتماد والإقفال والتصدير عند تنفيذها.</Empty>}</Panel></div>;
}

export function FinanceWorkspace(props: FinanceWorkspaceProps) {
  const { report } = props;
  const closed = Boolean(report.data.periods.find(period => period.month === report.query.month)?.closedAt);
  const context: Context = { ...props, writable: report.data.ready && !closed };
  const currentSection = sections.find(section => section.key === report.query.section)!;
  const visibleSections = sections.filter(section => !section.accountant || report.query.mode === 'accountant' || report.query.section === section.key);
  const exportQuery = href(report.query).split('?')[1];
  return <div className={styles.workspace} dir="rtl"><div className={`${styles.topline} ${styles.noPrint}`}><span className={styles.brand}><span className={styles.brandMark}><TrendingUp size={16} aria-hidden="true" /></span> تربح <span className={styles.muted}>/ المتابعة المالية</span></span><Link href="/admin" className={styles.back}>لوحة الإدارة <ArrowLeft size={13} aria-hidden="true" /></Link></div>
    <header className={styles.heading}><div><p className={styles.eyebrow}>FINANCE WORKSPACE</p><h1 className={styles.title}>{currentSection.label}</h1><p className={styles.subtitle}>كل مبلغ له مصدر، وكل التزام له متابعة. تجارة السلع المعتمدة · {monthTitle(report.query.month)}</p></div><div className={`${styles.actions} ${styles.noPrint}`}><div className={styles.modeSwitch} aria-label="طريقة العرض"><Link href={href(report.query, { mode: 'simple' })} className={report.query.mode === 'simple' ? styles.modeActive : ''} aria-current={report.query.mode === 'simple' ? 'page' : undefined}>عرض مبسط</Link><Link href={href(report.query, { mode: 'accountant' })} className={report.query.mode === 'accountant' ? styles.modeActive : ''} aria-current={report.query.mode === 'accountant' ? 'page' : undefined}>عرض المحاسب</Link></div>{props.canExport && <><a href={`/admin/finance/export?${exportQuery}&format=xlsx`} className={styles.secondaryButton}><Download size={15} aria-hidden="true" /> Excel</a><a href={`/admin/finance/export?${exportQuery}&format=print`} className={styles.secondaryButton} target="_blank" rel="noreferrer"><FileText size={15} aria-hidden="true" /> PDF / طباعة</a></>}</div></header>
    <nav className={`${styles.tabs} ${styles.noPrint}`} aria-label="أقسام المتابعة المالية">{visibleSections.map(section => <Link key={section.key} href={sectionHref(report.query, section.key)} className={`${styles.tab} ${report.query.section === section.key ? styles.activeTab : ''}`} aria-current={report.query.section === section.key ? 'page' : undefined}><section.icon size={15} aria-hidden="true" />{section.label}</Link>)}</nav>
    {!report.data.ready && <div className={styles.alert} role="alert"><CircleAlert size={19} aria-hidden="true" /><p><strong>مصادر المالية غير جاهزة بالكامل.</strong> إجراءات الحفظ معطلة حتى اكتمال تهيئة الجداول والتحقق منها. لا تعتبر غياب البيانات رصيدًا صفريًا مؤكدًا.</p></div>}
    {closed && <div className={styles.success}><LockKeyhole size={18} aria-hidden="true" /><p>هذا الشهر مقفل. يمكنك مراجعة سجلاته وتصديرها؛ التصحيح يسجل في فترة مفتوحة وفق السياسة.</p></div>}
    <PeriodFilters query={report.query} suppliers={report.data.suppliers} />
    {report.query.section === 'overview' && <Overview context={context} />}{report.query.section === 'suppliers' && <Suppliers context={context} />}{report.query.section === 'settlements' && <Settlements context={context} />}{report.query.section === 'budget' && <Budget context={context} />}{report.query.section === 'expenses' && <Expenses context={context} />}{report.query.section === 'invoices' && <InvoiceArchive context={context} />}{report.query.section === 'cashflow' && <Cashflow report={report} />}{report.query.section === 'month-end' && <MonthEnd report={report} />}{report.query.section === 'close' && <CloseMonth context={context} />}{report.query.section === 'reconciliation' && <Reconciliation report={report} />}{report.query.section === 'tax' && <TaxReview report={report} />}{report.query.section === 'ledger' && <Ledger report={report} />}
    <footer className={styles.footer}><span>تربح · المتابعة المالية للسلع المعتمدة</span><span>المحفظة وإعلانات الأفراد خارج نطاق هذا التقرير · جميع المبالغ بالريال السعودي</span></footer>
  </div>;
}
