import type {TaxRegistrationReport} from '@/lib/finance/tax-registration';
import {formatFinanceMoney} from '@/lib/finance/calculations';

function date(value:string){return new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{timeZone:'Asia/Riyadh',dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
export function TaxRegistrationMonitor({report}:{report:TaxRegistrationReport}){
 const red=report.alert==='100'||!!report.forecast?.projectedSoon;
 const warning=red||report.alert!=='normal'||!report.coverage.complete;
 const percent=(report.percentBps/100).toFixed(2);
 return <section aria-labelledby="tax-registration-title" dir="rtl" className="my-6 min-w-0 space-y-4 rounded-2xl border border-slate-200 bg-white p-4 text-slate-900 [overflow-wrap:anywhere] sm:p-6">
  <div><h2 id="tax-registration-title" className="text-xl font-bold">متابعة حد التسجيل الضريبي</h2><p className="mt-1 text-sm text-slate-600">التوريدات المؤكدة للمنصة، بعد الإشعارات الدائنة وعكسها، خلال آخر 12 شهرًا حتى الآن. هذا مجموع المصادر المؤكدة المتصلة، وليس إجمالي المنشأة النهائي.</p></div>
  <p className="text-sm text-slate-600">من {date(report.window.start)} إلى {date(report.window.endInclusive)} · آخر تحديث: {date(report.updatedAt)}</p>
  <dl className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">
   {[['التوريدات المؤكدة',formatFinanceMoney(report.confirmedTotalMinor)],['حد التسجيل المعتمد',formatFinanceMoney(report.thresholdMinor)],['نسبة الوصول إلى الحد',`${percent}%`],['المتبقي إلى الحد',formatFinanceMoney(report.remainingMinor)]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-3"><dt className="text-sm text-slate-600">{label}</dt><dd className="mt-1 text-lg font-bold">{value}</dd></div>)}
  </dl>
  <div role={warning?'alert':'status'} className={`rounded-xl border p-3 text-sm ${red?'border-red-300 bg-red-50 text-red-900':warning?'border-amber-300 bg-amber-50 text-amber-950':'border-slate-200 bg-slate-50'}`}>
   {report.alert==='100'?<p className="font-bold">بلغت التوريدات المؤكدة حد التسجيل أو تجاوزته؛ راجع متطلبات التسجيل.</p>:report.forecast?.projectedSoon?<p className="font-bold">قد تبلغ التوريدات المتوقعة خلال الاثني عشر شهرًا القادمة حد التسجيل؛ راجع التوقع والتسجيل الآن.</p>:report.alert!=='normal'?<p className="font-bold">تنبيه اقتراب من الحد: وصلت التوريدات المؤكدة إلى {percent}%.</p>:<p>بلغت المصادر المؤكدة {percent}% من الحد. انخفاض النسبة لا يثبت عدم وجود توريدات أخرى.</p>}
   <p className="mt-1">هذه متابعة وتنبيه فقط؛ لا تُفعّل الضريبة تلقائيًا ولا تغيّر حالة التسجيل. تعديل الحد وحالة الضريبة يتم عبر الإعدادات المعتمدة ومراجعة الصلاحيات.</p>
  </div>
  {!report.coverage.complete&&<div className="space-y-2 rounded-xl border border-amber-300 p-3"><h3 className="font-bold">التغطية غير مكتملة — توجد مصادر تحتاج مراجعة</h3><p className="text-sm">المبالغ أدناه غير مضافة إلى المجموع المؤكد، وقد تكون إجمالية شاملة للضريبة أو حركات غير مصنفة؛ لا تجمعها تلقائيًا معه.</p><ul className="space-y-2 text-sm">{report.coverage.gaps.map(gap=><li key={gap.code} className="rounded-lg bg-amber-50 p-2"><span>{gap.label}</span><span className="mt-1 block">عدد السجلات: {gap.count} · القيمة للمراجعة: {gap.amountMinor===null?'تعذر التحقق':formatFinanceMoney(gap.amountMinor)}</span></li>)}</ul></div>}
  <div className="space-y-1 text-sm"><h3 className="font-bold">تقدير التوريدات خلال الاثني عشر شهرًا القادمة</h3>{report.forecast?<><p>{formatFinanceMoney(report.forecast.lowMinor)} إلى {formatFinanceMoney(report.forecast.highMinor)}</p><p className="text-slate-600">نطاق مقارنة لسرعة المبيعات الصافية خلال آخر 30 و90 يومًا، بحدود التاريخ المرصود ({report.forecast.observedDays} يومًا)، ويشمل مبيعات الشهر الحالي.{report.forecast.monthsObserved===6?' تمت مقارنة آخر 3 و6 أشهر مكتملة أيضًا.':''} هذا امتداد حسابي للوتيرة الحالية، وليس توقعًا مضمونًا أو نطاق ثقة.</p></>:<p className="text-amber-900">التوقع غير متاح: {report.forecastUnavailableReason==='coverage_incomplete'?'تغطية المصادر ناقصة؛ يلزم استكمال المراجعة أولًا.':'يلزم تاريخ توريدات مؤكدة لا يقل عن 30 يومًا. لا يعني ذلك أن التوريدات المتوقعة أقل من الحد.'}</p>}</div>
  <details className="rounded-xl border border-slate-200 p-3 text-sm"><summary className="cursor-pointer font-bold">الأشهر الاثنا عشر المكتملة ونطاق المصادر</summary><div className="mt-3 space-y-2"><p>فحص نهاية الشهر: من {date(report.completedMonths.start)} حتى ما قبل {date(report.completedMonths.endExclusive)}: <strong>{formatFinanceMoney(report.completedMonths.totalMinor)}</strong>.</p><p>يُحتسب صافي فواتير بيع المنصة المؤكدة من سياسة معتمدة ومقبوض مطابق، بتاريخ التوريد/المقبوض، بما فيها التوريدات الخاضعة بمعدل صفر أو أثناء إيقاف احتساب الضريبة. لا تُحتسب قيمة الطلب والفاتورة والمقبوض أكثر من مرة.</p><p>تُستبعد التوريدات المعفاة وخارج النطاق والأصول الرأسمالية والسجلات ذات علامة اختبار صريحة وإيداعات المحفظة وأسعار إعلانات الأعضاء. الخدمات غير المصنفة والطلبات المدفوعة غير المؤكدة تظهر للمراجعة.</p><p>عدد التوريدات المؤكدة في الفترة: {report.confirmedSupplyCount} · سجلات اختبار مستبعدة: {report.excludedTestCount}.</p></div></details>
 </section>;
}
