import Link from 'next/link';
import { FieldOrderEditor } from '@/components/dynamic-ads/field-order-editor';
import { requireAction } from '@/lib/roles';
import { getSettingBool } from '@/lib/settings';
import { SMART_ADS_LAB_SETTING } from '@/lib/dynamic-ads/access';
import { listDynamicAdminDrafts, listDynamicEntities } from '@/lib/dynamic-ads/repository';
import { addDynamicEntityAction, addDynamicFieldAction, addDynamicGroupAction, deleteDynamicFieldAction, reorderDynamicFieldAction, setSmartAdsLabEnabledAction, toggleDynamicEntityAction, toggleDynamicFieldAction } from './actions';

export const dynamic = 'force-dynamic';
const input = 'h-10 w-full rounded-lg border px-3 text-sm';
const types = [['text','نص قصير'],['textarea','نص طويل'],['number','رقم'],['decimal','سعر / رقم عشري'],['date','تاريخ'],['select','اختيار واحد'],['multiselect','اختيار متعدد'],['boolean','نعم / لا'],['media','صورة'],['file','ملف'],['url','رابط'],['location','موقع على الخريطة']];
export default async function SmartAdsAdminPage({ searchParams }: { searchParams: Promise<{ entity?: string }> }) {
  await requireAction('users','edit');
  const [enabled, entities, drafts, query] = await Promise.all([getSettingBool(SMART_ADS_LAB_SETTING,false),listDynamicEntities(true),listDynamicAdminDrafts(),searchParams]);
  const selected = entities.find((entity) => String(entity.id) === query.entity) ?? entities[0];
  return <main className="mx-auto max-w-6xl space-y-5" dir="rtl">
    <section className="rounded-2xl border-2 border-primary/20 bg-primary/5 p-5"><h1 className="text-2xl font-extrabold text-primary">إدارة حقول الكيانات</h1><p className="mt-1 text-sm text-slate-600">مختبر خاص؛ لا يغير الإعلانات المنشورة.</p><form action={setSmartAdsLabEnabledAction} className="mt-3 flex gap-2"><input type="hidden" name="enabled" value={enabled?'0':'1'}/><button className="rounded-lg bg-primary px-4 py-2 font-bold text-white">{enabled?'إيقاف المختبر':'تفعيل المختبر'}</button>{enabled&&<Link href="/lab/smart-ads" className="rounded-lg border px-4 py-2 font-bold text-primary">فتح تجربة الإضافة</Link>}</form></section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="font-extrabold text-primary">الكيانات والأقسام والحقول</h2><form className="mt-3 flex max-w-md gap-2"><select name="entity" defaultValue={selected ? String(selected.id) : ''} className={input} onChange={(event) => event.currentTarget.form?.requestSubmit()}>{entities.map(entity=><option key={entity.id} value={entity.id}>{entity.icon} {entity.name}</option>)}</select><button className="rounded-lg border px-3 text-sm font-bold text-primary">عرض</button></form><p className="mt-2 text-sm text-slate-500">رتّب الحقول بأرقام الإدخال والعرض؛ الرقم الأصغر يظهر أولاً.</p><div className="mt-4 space-y-4">{selected && <article key={selected.id} className="rounded-xl border p-4"><div className="flex items-center justify-between"><b>{selected.icon} {selected.name}</b><form action={toggleDynamicEntityAction}><input type="hidden" name="id" value={selected.id}/><input type="hidden" name="active" value={selected.active?'0':'1'}/><button className="text-sm font-bold text-primary">{selected.active?'إيقاف':'تفعيل'}</button></form></div>
      <div className="mt-3 grid gap-3 lg:grid-cols-2">{selected.groups.map(group=><div key={group.id} className="rounded-lg bg-slate-50 p-3"><h3 className="font-bold">{group.label}</h3><p className="mt-1 text-xs text-slate-500">اسحب الحقل لترتيب الإدخال.</p><div className="mt-2"><FieldOrderEditor fields={selected.fields.filter(field=>field.groupId===group.id)} action={reorderDynamicFieldAction}/></div></div>)}</div>
      <form action={addDynamicGroupAction} className="mt-3 grid gap-2 rounded-lg bg-slate-50 p-3 md:grid-cols-5"><input type="hidden" name="entity_id" value={selected.id}/><input name="label" required placeholder="اسم قسم جديد" className={input}/><input name="key" required pattern="[a-z][a-z0-9_]{1,63}" placeholder="section_key" className={input}/><input name="input_order" type="number" defaultValue="99" className={input}/><input name="display_order" type="number" defaultValue="99" className={input}/><button className="rounded-lg bg-primary px-3 text-white">إضافة قسم</button></form>
      <form action={addDynamicFieldAction} className="mt-3 grid gap-2 rounded-lg border border-primary/15 p-3 md:grid-cols-4"><input type="hidden" name="entity_id" value={selected.id}/><select name="group_id" className={input}>{selected.groups.map(group=><option key={group.id} value={group.id}>{group.label}</option>)}</select><input name="label" required placeholder="اسم الحقل" className={input}/><input name="key" required pattern="[a-z][a-z0-9_]{1,63}" placeholder="field_key" className={input}/><select name="type" className={input}>{types.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><input name="placeholder" placeholder="نص مساعد" className={input}/><textarea name="options" placeholder="خيارات الاختيار: خيار بكل سطر" className="min-h-10 rounded border p-2 text-sm"/><input name="input_order" type="number" defaultValue="99" className={input}/><input name="display_order" type="number" defaultValue="99" className={input}/><div className="flex flex-wrap gap-3 text-sm"><label><input name="required" value="1" type="checkbox"/> مطلوب</label><label><input name="searchable" value="1" type="checkbox" defaultChecked/> بحث</label><label><input name="input_visible" value="1" type="checkbox" defaultChecked/> إدخال</label><label><input name="display_visible" value="1" type="checkbox" defaultChecked/> عرض</label><button className="rounded-lg bg-primary px-3 py-2 font-bold text-white">حفظ الحقل</button></div></form></article>}</div></section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="font-extrabold text-primary">سجل المسودات</h2><p className="mt-2 text-sm text-slate-600">{drafts.length} مسودات اختبار محفوظة.</p></section>
  </main>;
}
