'use client';
import { useMemo, useState } from 'react';
import type { DynamicEntity } from '@/lib/dynamic-ads/types';

export function DynamicAdForm({ entities, action, error }: { entities: DynamicEntity[]; action: (formData: FormData) => void | Promise<void>; error?: string }) {
  const [entityKey, setEntityKey] = useState('auto');
  const entity = useMemo(() => entities.find((item) => item.key === entityKey), [entities, entityKey]);
  const field = 'h-11 w-full rounded-xl border-2 border-primary/20 bg-white px-3 text-sm outline-none focus:border-primary';
  return <form action={action} className="mx-auto max-w-2xl space-y-4" dir="rtl">
    <div className="rounded-2xl border-2 border-primary/20 bg-primary/5 p-4"><h1 className="text-xl font-extrabold text-primary">مختبر الإعلانات الذكية</h1><p className="mt-1 text-sm text-slate-600">تجربة خاصة: تحفظ مسودة للتحليل فقط ولا تنشر إعلاناً أو تخصم رصيداً.</p></div>
    {error && <div className="rounded-xl border border-red-300 bg-red-50 p-3 text-sm font-bold text-red-800">{error === 'title' ? 'أدخل عنوان الإعلان.' : error === 'fields' ? 'أكمل الحقول المطلوبة لنوع الإعلان.' : 'تعذر اختيار نوع الإعلان.'}</div>}
    <section className="space-y-3 rounded-2xl border bg-white p-4 shadow-sm"><label className="block text-sm font-extrabold">اختر نوع الإعلان<select name="entity_key" value={entityKey} onChange={(event) => setEntityKey(event.target.value)} className={`${field} mt-1`}><option value="auto">✨ لا أعرف، دع الذكاء يحدد</option>{entities.filter((item) => item.active).map((item) => <option key={item.key} value={item.key}>{item.icon} {item.name}</option>)}</select></label><label className="block text-sm font-extrabold">عنوان الإعلان<input name="title" required className={`${field} mt-1`} placeholder="مثال: جيب لكزس 2020 فل كامل" /></label><label className="block text-sm font-extrabold">الوصف<textarea name="description" className="mt-1 min-h-28 w-full rounded-xl border-2 border-primary/20 p-3 text-sm outline-none focus:border-primary" placeholder="اكتب التفاصيل كما تعرفها، وسيقترح المحلل النواقص." /></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-extrabold">السعر (اختياري)<input name="price" type="number" min="0" step="0.01" className={`${field} mt-1`} /></label><label className="block text-sm font-extrabold">الموقع النصي (اختياري)<input name="location" className={`${field} mt-1`} placeholder="المدينة أو الحي" /></label></div></section>
    {entity && <section className="space-y-3 rounded-2xl border-2 border-sky-200 bg-sky-50 p-4"><h2 className="font-extrabold text-primary">مواصفات {entity.name}</h2><div className="grid gap-3 sm:grid-cols-2">{entity.fields.map((item) => <label key={item.key} className="block text-sm font-bold">{item.label}{item.required && <span className="text-red-600"> *</span>}{item.type === 'textarea' ? <textarea name={`dynamic_${item.key}`} required={item.required} className="mt-1 min-h-24 w-full rounded-xl border p-3" /> : item.type === 'select' ? <select name={`dynamic_${item.key}`} required={item.required} className={`${field} mt-1`}><option value="">اختر</option>{item.options.map((option) => <option key={option}>{option}</option>)}</select> : item.type === 'boolean' ? <select name={`dynamic_${item.key}`} className={`${field} mt-1`}><option value="">غير محدد</option><option value="true">نعم</option><option value="false">لا</option></select> : <input name={`dynamic_${item.key}`} type={item.type === 'number' ? 'number' : 'text'} required={item.required} className={`${field} mt-1`} />}</label>)}</div></section>}
    <button className="w-full rounded-xl bg-primary px-5 py-3 font-extrabold text-white shadow">حلّل الإعلان وأنشئ المعاينة الخاصة</button>
  </form>;
}
