'use client';
import { useMemo, useState } from 'react';
import type { DynamicEntity } from '@/lib/dynamic-ads/types';

const control = 'mt-1 h-11 w-full rounded-xl border-2 border-primary/20 bg-white px-3 text-sm outline-none focus:border-primary';
export function DynamicAdForm({ entities, action, error }: { entities: DynamicEntity[]; action: (formData: FormData) => void | Promise<void>; error?: string }) {
  const [entityKey, setEntityKey] = useState('auto'); const entity = useMemo(()=>entities.find(item=>item.key===entityKey),[entities,entityKey]);
  return <form action={action} className="mx-auto max-w-3xl space-y-4" dir="rtl"><header className="rounded-3xl bg-gradient-to-l from-primary to-sky-500 p-5 text-white shadow"><h1 className="text-2xl font-extrabold">تجربة إضافة إعلان ذكي</h1><p className="mt-1 text-sm opacity-90">مسودة اختبار خاصة فقط — لا نشر ولا خصم رصيد.</p></header>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">أكمل الحقول المطلوبة ثم أعد المحاولة.</p>}
    <section className="grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-2"><label className="text-sm font-bold">نوع الإعلان<select name="entity_key" value={entityKey} onChange={e=>setEntityKey(e.target.value)} className={control}><option value="auto">دع الذكاء يقترح النوع</option>{entities.filter(e=>e.active).map(e=><option key={e.key} value={e.key}>{e.icon} {e.name}</option>)}</select></label><label className="text-sm font-bold">عنوان الإعلان<input name="title" required className={control} placeholder="اكتب عنواناً واضحاً"/></label><label className="text-sm font-bold sm:col-span-2">الوصف<textarea name="description" className="mt-1 min-h-28 w-full rounded-xl border-2 border-primary/20 p-3 text-sm" placeholder="التفاصيل التي تعرفها عن الإعلان"/></label><label className="text-sm font-bold">السعر (اختياري)<input name="price" type="number" min="0" step="0.01" className={control}/></label><label className="text-sm font-bold">الموقع النصي (اختياري)<input name="location" className={control} placeholder="المدينة أو الحي"/></label></section>
    {entity&&entity.groups.sort((a,b)=>a.inputOrder-b.inputOrder).map(group=>{const fields=entity.fields.filter(f=>f.groupId===group.id&&f.inputVisible).sort((a,b)=>(a.inputOrder??999)-(b.inputOrder??999)); if(!fields.length)return null; return <section key={group.id} className="rounded-2xl border border-sky-200 bg-sky-50/60 p-4"><h2 className="font-extrabold text-primary">{group.label}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{fields.map(field=><Field key={field.key} field={field}/>)}</div></section>})}
    <button className="w-full rounded-xl bg-primary px-5 py-3 font-extrabold text-white shadow">حلّل الإعلان وأنشئ المعاينة</button></form>;
}
function Field({ field }: { field: DynamicEntity['fields'][number] }) { const name=`dynamic_${field.key}`; const label=<>{field.label}{field.required&&<span className="text-red-600"> *</span>}</>; if(field.type==='textarea')return <label className="text-sm font-bold sm:col-span-2">{label}<textarea name={name} required={field.required} placeholder={field.placeholder} className="mt-1 min-h-24 w-full rounded-xl border p-3"/></label>; if(field.type==='select')return <label className="text-sm font-bold">{label}<select name={name} required={field.required} className={control}><option value="">اختر</option>{field.options.map(o=><option key={o}>{o}</option>)}</select></label>; if(field.type==='multiselect')return <fieldset className="text-sm font-bold sm:col-span-2"><legend>{label}</legend><div className="mt-2 flex flex-wrap gap-2">{field.options.map(o=><label key={o} className="rounded-lg border bg-white px-3 py-2 text-sm font-normal"><input name={name} value={o} type="checkbox" className="ml-1"/>{o}</label>)}</div></fieldset>; if(field.type==='boolean')return <label className="text-sm font-bold">{label}<select name={name} className={control}><option value="">غير محدد</option><option value="true">نعم</option><option value="false">لا</option></select></label>; return <label className="text-sm font-bold">{label}<input name={name} required={field.required} placeholder={field.placeholder} type={field.type==='number'||field.type==='decimal'?'number':field.type==='date'?'date':field.type==='url'?'url':'text'} step={field.type==='decimal'?'0.01':undefined} className={control}/></label>; }
