'use client';
import { useEffect, useRef, useState } from 'react';
import { Expand, Monitor, Smartphone, X } from 'lucide-react';
import { TopupCampaignBannerView } from '@/components/topup-campaign-banner-view';
import { TOPUP_BANNER_HEIGHTS, TOPUP_BANNER_TEMPLATES, TOPUP_BANNER_WIDTHS, type TopupCampaignPresentation } from '@/lib/topup-campaign-presentation';

const defaultTiers = [{ amount: 100, bonus: 10 }, { amount: 200, bonus: 25 }, { amount: 300, bonus: 40 }];
export function TopupBannerStudio() {
  const root = useRef<HTMLElement>(null); const [presentation, setPresentation] = useState<TopupCampaignPresentation>({ template: 'heritage', width: 'full', height: 'medium' }); const [tiers, setTiers] = useState(defaultTiers); const [open, setOpen] = useState(false); const [device, setDevice] = useState<'mobile' | 'desktop'>('mobile');
  useEffect(() => { const form = root.current?.closest('form'); if (!form) return; const read = () => { const amounts = [...form.querySelectorAll<HTMLInputElement>('input[name="tierAmount"]')]; const bonuses = [...form.querySelectorAll<HTMLInputElement>('input[name="tierBonus"]')]; const next = amounts.map((input, i) => ({ amount: Number(input.value) || 0, bonus: Number(bonuses[i]?.value) || 0 })).filter((t) => t.amount > 0 && t.bonus > 0); setTiers(next.length ? next : [{ amount: 100, bonus: 10 }]); }; form.addEventListener('input', read); return () => form.removeEventListener('input', read); }, []);
  return <section ref={root} className="space-y-3 rounded-xl border-2 border-sky-200 bg-sky-50/50 p-3"><div><h3 className="font-extrabold text-sky-900">🎨 تصميم البانر</h3><p className="text-[11px] text-muted-foreground">اختر التصميم والمقاس ثم شاهد النتيجة داخل صفحة تحاكي الرئيسية قبل النشر.</p></div><input type="hidden" name="bannerTemplate" value={presentation.template} /><input type="hidden" name="bannerWidth" value={presentation.width} /><input type="hidden" name="bannerHeight" value={presentation.height} /><label className="block text-xs font-bold text-sky-900">تصميم البانر<select value={presentation.template} onChange={(e) => setPresentation((p) => ({ ...p, template: e.target.value as TopupCampaignPresentation['template'] }))} className="mt-1 w-full rounded-lg border bg-white p-2 text-sm">{TOPUP_BANNER_TEMPLATES.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label><div className="grid gap-2 sm:grid-cols-2"><label className="text-xs font-bold text-sky-900">عرض البانر<select value={presentation.width} onChange={(e) => setPresentation((p) => ({ ...p, width: e.target.value as TopupCampaignPresentation['width'] }))} className="mt-1 w-full rounded-lg border bg-white p-2 text-sm">{TOPUP_BANNER_WIDTHS.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label><label className="text-xs font-bold text-sky-900">ارتفاع البانر<select value={presentation.height} onChange={(e) => setPresentation((p) => ({ ...p, height: e.target.value as TopupCampaignPresentation['height'] }))} className="mt-1 w-full rounded-lg border bg-white p-2 text-sm">{TOPUP_BANNER_HEIGHTS.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label></div><button type="button" onClick={() => setOpen(true)} className="btn-3d flex w-full items-center justify-center gap-2 rounded-lg bg-[#041632] px-4 py-2.5 text-sm font-black text-amber-300"><Expand className="h-4 w-4" /> عرض على الصفحة</button>{open && <PreviewDialog device={device} setDevice={setDevice} close={() => setOpen(false)} presentation={presentation} tiers={tiers} />}</section>;
}
function PreviewDialog({ device, setDevice, close, presentation, tiers }: { device: 'mobile' | 'desktop'; setDevice: (device: 'mobile' | 'desktop') => void; close: () => void; presentation: TopupCampaignPresentation; tiers: { amount: number; bonus: number }[] }) { return <div className="fixed inset-0 z-[100] overflow-y-auto bg-slate-950/75 p-3" role="dialog" aria-modal="true"><div className="mx-auto max-w-6xl rounded-2xl bg-white p-3 shadow-2xl"><div className="mb-3 flex items-center justify-between"><b className="text-sm text-slate-900">معاينة على الصفحة — لا يتم الحفظ أو النشر</b><span className="flex items-center gap-1"><button type="button" onClick={() => setDevice('mobile')} className={`rounded p-2 ${device === 'mobile' ? 'bg-primary text-white' : 'bg-slate-100'}`}><Smartphone className="h-4 w-4" /></button><button type="button" onClick={() => setDevice('desktop')} className={`rounded p-2 ${device === 'desktop' ? 'bg-primary text-white' : 'bg-slate-100'}`}><Monitor className="h-4 w-4" /></button><button type="button" onClick={close} className="rounded p-2 text-slate-700 hover:bg-slate-100" aria-label="إغلاق"><X className="h-5 w-5" /></button></span></div><div className={`mx-auto overflow-hidden rounded-xl border bg-slate-50 shadow-inner ${device === 'mobile' ? 'max-w-[390px]' : 'max-w-5xl'}`}><div className="flex h-14 items-center justify-between bg-[#041632] px-4 text-xs font-black text-amber-300"><span className="text-lg">تربح</span><span>الرئيسية · المتاجر · أضف إعلان · محفظتي</span><span>☰</span></div><div className="space-y-3 p-3"><div className="rounded-xl bg-slate-200 px-3 py-2 text-center text-xs font-bold text-slate-500">مساحة إعلان علوي — لا تتغير بالحملة</div><TopupCampaignBannerView tiers={tiers} presentation={presentation} preview /><h4 className="pt-2 text-xl font-black text-sky-700">🎯 يهمك الآن</h4><div className="grid grid-cols-2 gap-2"><div className="h-28 rounded-xl border bg-white p-3 text-xs text-slate-400">إعلان نشط</div><div className="h-28 rounded-xl border bg-white p-3 text-xs text-slate-400">إعلان نشط</div></div></div></div></div></div>; }
