import Link from 'next/link';
import { requireSmartAdsLab } from '@/lib/dynamic-ads/access';
import { listDynamicEntities, searchDynamicDrafts } from '@/lib/dynamic-ads/repository';

export const dynamic = 'force-dynamic';
export const metadata = { robots: { index: false, follow: false }, title: 'بحث مختبر الإعلانات الذكية' };
export default async function SmartAdsSearchPage({ searchParams }: { searchParams: Promise<{ q?: string; entity?: string }> }) {
  const session = await requireSmartAdsLab(); const query = await searchParams; const entities = await listDynamicEntities(); const selected = entities.find((entity) => String(entity.id) === query.entity); const drafts = await searchDynamicDrafts({ userId: session.uid, entityId: selected?.id, term: query.q, limit: 50 });
  return <div className="mx-auto max-w-3xl space-y-4" dir="rtl"><div className="rounded-2xl border-2 border-primary/20 bg-primary/5 p-4"><h1 className="text-xl font-extrabold text-primary">بحث مختبر الإعلانات الذكية</h1><p className="mt-1 text-sm text-slate-600">بحث خاص في مسوداتك التجريبية فقط.</p></div><form className="grid gap-2 rounded-xl border bg-white p-3 sm:grid-cols-[1fr_180px_auto]"><input name="q" defaultValue={query.q} placeholder="ابحث في العنوان أو الوصف" className="h-11 rounded-lg border px-3 text-sm" /><select name="entity" defaultValue={query.entity || ''} className="h-11 rounded-lg border px-3 text-sm"><option value="">كل الكيانات</option>{entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.icon} {entity.name}</option>)}</select><button className="rounded-lg bg-primary px-4 text-sm font-extrabold text-white">بحث</button></form><div className="space-y-2">{drafts.map((draft) => <Link key={draft.id} href={`/lab/smart-ads/${draft.id}/analyze`} className="block rounded-xl border bg-white p-3 hover:border-primary"><b>#{draft.id} - {draft.title}</b><p className="mt-1 line-clamp-2 text-sm text-slate-600">{draft.description}</p><span className="mt-2 inline-block text-xs text-primary">{draft.analysis.entityKey || 'غير محدد'} - جودة {draft.analysis.quality}%</span></Link>)}{!drafts.length && <p className="rounded-xl border bg-white p-6 text-center text-sm text-slate-500">لا توجد مسودات مطابقة.</p>}</div></div>;
}
