'use client';

import Link from 'next/link';
import { useState } from 'react';
import { useFormStatus } from 'react-dom';
import { Building2, Check, ChevronDown, KeyRound, LockKeyhole, Search, ShieldAlert, ShieldCheck, Users } from 'lucide-react';
import { ACTION_LABELS, MODULES, PERMISSIONS } from '@/lib/access-control/catalog';

type Department = { id: string; name: string; active: boolean };
type AccessRole = { id: string; name: string; departmentId: string; active: boolean; permissions: string[]; userCount: number };
type AccessData = { ready: boolean; departments: Department[]; roles: AccessRole[]; assignments: { userId: number; roleIds: string[] }[]; users: { id: number; name: string; userName: string | null; phone: string | null; enabled: boolean }[]; audit: { id: string; at: string; actorId: number | string | null; action: string; target: string; reason: string; before: unknown; after: unknown; ip: string | null; sessionFingerprint: string | null }[] };
type Action = (form: FormData) => Promise<void>;
type Props = { data: AccessData; currentUserId: number; canManage: boolean; q: string; selectedUserId?: number; section: string; notice: string; saveDepartmentAction: Action; saveRoleAction: Action; assignAction: Action };
const input = 'mt-1 block min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-[#16294A] focus:border-amber-400 focus:outline-none focus:ring-2 focus:ring-amber-100';
const button = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#16294A] px-5 py-2 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40';
const secondary = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold text-[#16294A]';
const errors: Record<string, string> = { access_schema_not_ready: 'تهيئة إدارة الوصول غير مكتملة. لم يُحفظ التغيير.', access_not_initialized: 'إدارة الوصول تنتظر التهيئة المعتمدة قبل استخدامها.', access_forbidden: 'لا تملك صلاحية تنفيذ هذا التغيير.', access_input_invalid: 'راجع الاسم والحقول المطلوبة وسبب التغيير.', access_unknown_permission: 'تتضمن المدخلات صلاحية غير مسجلة. حدّث الصفحة وأعد المراجعة.', access_department_missing: 'القسم المختار غير موجود.', access_role_missing: 'أحد الأدوار المختارة لم يعد متاحًا. حدّث الصفحة.', access_user_missing: 'الموظف المختار غير موجود.', access_self_escalation: 'لا يمكن استخدام هذا الإجراء لزيادة صلاحيات حسابك الحالي.', access_last_manager: 'لم يُحفظ التغيير لأنه سيزيل آخر مسؤول يستطيع إدارة الوصول.', access_mfa_required: 'يجب أن يربط الموظف تطبيق التحقق من صفحة أمان الحساب قبل إسناد الصلاحيات.' };
function Submit({ children, disabled }: { children: React.ReactNode; disabled?: boolean }) { const status = useFormStatus(); return <button className={button} disabled={disabled || status.pending}>{status.pending ? 'جارٍ الحفظ…' : children}</button>; }
function Reason() { return <label className="block text-sm font-bold">سبب التغيير<textarea name="reason" required minLength={3} maxLength={1000} rows={2} className={input} placeholder="ما التغيير المطلوب، ولماذا؟" /></label>; }
function Status({ active }: { active: boolean }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${active ? 'bg-emerald-50 text-emerald-800' : 'bg-slate-100 text-slate-500'}`}>{active ? 'نشط' : 'معطّل'}</span>; }

function PermissionMatrix({ selected, onChange, disabled }: { selected: Set<string>; onChange: (keys: Set<string>) => void; disabled: boolean }) {
  const [search, setSearch] = useState('');
  function toggle(key: string, checked: boolean) { const next = new Set(selected); if (checked) next.add(key); else next.delete(key); onChange(next); }
  const sensitive = PERMISSIONS.filter(permission => permission.sensitive);
  return <div className="space-y-4"><label className="block text-sm font-bold">البحث في الوحدات والإجراءات<input type="search" value={search} onChange={event => setSearch(event.target.value)} className={input} placeholder="مثال: الموردون، تصدير، اعتماد…" /></label>
    <div className="overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[650px] text-right text-xs"><caption className="bg-slate-50 p-3 text-right text-xs text-slate-600">الصلاحيات العادية. الخانة غير الموجودة تعني أن الإجراء غير مسجل لهذه الوحدة.</caption><thead><tr className="bg-slate-50"><th className="p-3">الوحدة</th><th className="p-3">الإجراءات المسموحة</th></tr></thead><tbody>{MODULES.filter(module => `${module.label} ${module.key} ${module.actions.map(action => ACTION_LABELS[action] || action).join(' ')}`.toLowerCase().includes(search.toLowerCase())).map(module => { const permissions = PERMISSIONS.filter(permission => permission.module === module.key && !permission.sensitive); if (!permissions.length) return null; return <tr key={module.key} className="border-t border-slate-100"><th className="w-44 p-3 font-bold">{module.label}</th><td className="p-3"><div className="flex flex-wrap gap-x-5 gap-y-3">{permissions.map(permission => <label key={permission.key} className="flex min-h-8 cursor-pointer items-center gap-2"><input type="checkbox" checked={selected.has(permission.key)} onChange={event => toggle(permission.key, event.target.checked)} disabled={disabled} className="h-4 w-4 accent-[#16294A]" /><span>{ACTION_LABELS[permission.action] || permission.label}</span></label>)}</div></td></tr>; })}</tbody></table></div>
    <details className="rounded-xl border border-amber-200 bg-amber-50/60 p-4" open><summary className="flex cursor-pointer items-center gap-2 text-sm font-bold text-amber-900"><ShieldAlert size={17} /> صلاحيات حساسة · {sensitive.filter(permission => selected.has(permission.key)).length} محددة</summary><p className="my-3 text-xs leading-6 text-amber-900">تُمنح كل صلاحية حساسة صراحةً. الأدوار الجديدة تبدأ دون أي صلاحية، ولا تمنح مشاهدة الصفحة حق اعتماد أو حذف أو تصدير.</p><div className="grid gap-3 sm:grid-cols-2">{sensitive.filter(permission => `${permission.label} ${MODULES.find(module => module.key === permission.module)?.label || ''}`.toLowerCase().includes(search.toLowerCase())).map(permission => <label key={permission.key} className="flex cursor-pointer items-start gap-2 rounded-lg border border-amber-100 bg-white p-3 text-xs"><input type="checkbox" checked={selected.has(permission.key)} onChange={event => toggle(permission.key, event.target.checked)} disabled={disabled} className="mt-1 h-4 w-4 shrink-0 accent-amber-600" /><span><strong>{MODULES.find(module => module.key === permission.module)?.label}</strong><span className="mt-1 block text-slate-600">{ACTION_LABELS[permission.action] || permission.label}</span></span></label>)}</div></details>
    {[...selected].map(key => <input key={key} type="hidden" name="permissions" value={key} />)}
  </div>;
}
function RoleEditor({ role, departments, action, canManage }: { role?: AccessRole; departments: Department[]; action: Action; canManage: boolean }) {
  const [selected, setSelected] = useState(new Set(role?.permissions || []));
  const initial = new Set(role?.permissions || []);
  const added = [...selected].filter(key => !initial.has(key)).length;
  const removed = [...initial].filter(key => !selected.has(key)).length;
  return <form action={action} className="space-y-4">{role && <input type="hidden" name="id" value={role.id} />}<fieldset disabled={!canManage} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">اسم الدور<input name="name" required maxLength={120} defaultValue={role?.name} className={input} placeholder="مثال: مراجع حسابات الموردين" /></label><label className="text-sm font-bold">القسم<select name="departmentId" required defaultValue={role?.departmentId || ''} className={input}><option value="" disabled>اختر القسم</option>{departments.map(department => <option key={department.id} value={department.id}>{department.name}{department.active ? '' : ' (معطّل)'}</option>)}</select></label></div><label className="flex items-center gap-2 text-sm"><input name="active" value="1" type="checkbox" defaultChecked={role?.active ?? true} className="h-4 w-4 accent-[#16294A]" /> الدور نشط</label><PermissionMatrix selected={selected} onChange={setSelected} disabled={!canManage} /><Reason /></fieldset><div className="flex flex-wrap items-center justify-between gap-3 border-t pt-4"><p className="text-xs text-slate-600">المحدد: {selected.size} · إضافة {added} · إزالة {removed}{role && ` · يتأثر ${role.userCount} موظف`}</p><Submit disabled={!canManage}>{role ? 'حفظ تغييرات الدور' : 'إنشاء الدور'}</Submit></div></form>;
}
function Assignment({ data, user, currentUserId, action, canManage }: { data: AccessData; user: AccessData['users'][number]; currentUserId: number; action: Action; canManage: boolean }) {
  const assigned = data.assignments.find(item => item.userId === user.id)?.roleIds || [];
  const [selected, setSelected] = useState(new Set(assigned));
  const effective = new Set(data.roles.filter(role => user.enabled && selected.has(role.id) && role.active && data.departments.some(department => department.id === role.departmentId && department.active)).flatMap(role => role.permissions));
  return <form action={action} className="space-y-4"><input type="hidden" name="userId" value={user.id} /><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-extrabold">{user.name || user.userName || `موظف #${user.id}`}</h3><p className="text-xs text-slate-500">#{user.id}{currentUserId === user.id ? ' · حسابك الحالي' : ''} · {user.enabled ? 'الحساب متاح' : 'الحساب غير متاح'}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">{selected.size} أدوار · {effective.size} صلاحيات فعلية</span></div><fieldset disabled={!canManage} className="space-y-4"><legend className="mb-3 text-xs text-slate-500">يمكن إسناد أكثر من دور. الدور أو القسم المعطّل لا يمنح وصولًا.</legend><div className="grid gap-3 sm:grid-cols-2">{data.roles.map(role => <label key={role.id} className={`flex cursor-pointer items-start gap-2 rounded-xl border p-3 text-sm ${selected.has(role.id) ? 'border-[#16294A] bg-slate-50' : 'border-slate-200'}`}><input name="roleIds" type="checkbox" value={role.id} checked={selected.has(role.id)} disabled={!user.enabled && !selected.has(role.id)} onChange={event => { const next = new Set(selected); if (event.target.checked) next.add(role.id); else next.delete(role.id); setSelected(next); }} className="mt-1 h-4 w-4 accent-[#16294A]" /><span><strong>{role.name}</strong><span className="mt-1 block text-xs text-slate-500">{data.departments.find(department => department.id === role.departmentId)?.name || role.departmentId} · {role.active ? 'نشط' : 'معطّل'}</span></span></label>)}</div><Reason /></fieldset><details className="rounded-xl bg-slate-50 p-3 text-xs"><summary className="cursor-pointer font-bold">معاينة الوصول الفعلي قبل الحفظ</summary><div className="mt-3 flex flex-wrap gap-2">{[...effective].map(key => <span key={key} className="rounded-lg border bg-white px-2 py-1">{PERMISSIONS.find(permission => permission.key === key)?.label || key}</span>)}{!effective.size && <p>لا توجد صلاحيات فعلية من الأدوار المحددة.</p>}</div></details><p className="text-xs text-slate-500">تُراجع صلاحيتك وحدود إدارة الوصول عند الحفظ. إسناد الأدوار لا يغير الحسابات أو المعادلات المالية.</p><Submit disabled={!canManage || (!user.enabled && selected.size > 0)}>حفظ أدوار الموظف</Submit></form>;
}

export function AccessControlWorkspace(props: Props) {
  const { data, canManage, currentUserId } = props;
  const editable = canManage && data.ready;
  const tabs = [{ key: 'roles', label: 'الأدوار والصلاحيات', icon: KeyRound }, { key: 'users', label: 'الموظفون وإسناد الأدوار', icon: Users }, { key: 'departments', label: 'الأقسام', icon: Building2 }, { key: 'audit', label: 'سجل التغييرات', icon: ShieldCheck }];
  const section = tabs.some(tab => tab.key === props.section) ? props.section : 'roles';
  const selectedUser = data.users.find(user => user.id === props.selectedUserId);
  return <main dir="rtl" className="space-y-5 rounded-2xl border border-slate-200 bg-[#F7F6F0] p-4 text-[#16294A] md:p-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-widest text-slate-500">تربح / إدارة الوصول</p><h1 className="mt-2 text-2xl font-extrabold md:text-3xl">الأقسام والأدوار والصلاحيات</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-600">وصول واضح لكل موظف، من مشاهدة القسم إلى الإجراء الذي يُسمح له بتنفيذه. الصلاحيات تُراجع في الخادم عند كل إجراء.</p></div><span className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-bold"><LockKeyhole size={15} />{canManage ? 'إدارة الوصول' : 'عرض فقط'}</span></header>
    {!data.ready && <p role="alert" className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm">إدارة الوصول تنتظر التهيئة المعتمدة. جميع عمليات التغيير معطلة.</p>}{props.notice && <p role={props.notice === 'saved' ? 'status' : 'alert'} className={`rounded-xl border p-4 text-sm ${props.notice === 'saved' ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : 'border-amber-300 bg-amber-50 text-amber-900'}`}>{props.notice === 'saved' ? 'حُفظ التغيير وسُجل في سجل التدقيق.' : errors[props.notice] || 'تعذر حفظ التغيير. راجع المدخلات وصلاحيتك ثم أعد المحاولة.'}</p>}
    <div className="grid grid-cols-3 gap-3">{[{ label: 'الأقسام', value: data.departments.length }, { label: 'الأدوار النشطة', value: data.roles.filter(role => role.active).length }, { label: 'الموظفون في النتائج', value: data.users.length }].map(item => <div key={item.label} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">{item.label}</p><p className="mt-1 text-2xl font-extrabold">{item.value}</p></div>)}</div>
    <nav aria-label="أقسام إدارة الوصول" className="flex gap-2 overflow-x-auto border-b pb-3">{tabs.map(tab => <Link key={tab.key} href={`/admin/access-control?section=${tab.key}`} className={`flex min-h-11 items-center gap-2 whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold ${section === tab.key ? 'bg-[#16294A] text-white' : 'bg-white text-slate-600'}`} aria-current={section === tab.key ? 'page' : undefined}><tab.icon size={16} />{tab.label}</Link>)}</nav>
    {section === 'roles' && <div className="space-y-4">{editable && <details className="rounded-2xl border border-amber-300 bg-white p-5"><summary className="flex cursor-pointer items-center gap-2 font-extrabold"><KeyRound size={18} className="text-amber-600" /> إنشاء دور جديد <span className="text-xs font-normal text-slate-500">يبدأ دون صلاحيات</span></summary><div className="mt-5"><RoleEditor departments={data.departments} action={props.saveRoleAction} canManage={editable} /></div></details>}{data.roles.map(role => <details key={role.id} className="rounded-2xl border border-slate-200 bg-white p-5"><summary className="flex cursor-pointer flex-wrap items-center justify-between gap-3"><span><strong>{role.name}</strong><span className="mt-1 block text-xs text-slate-500">{data.departments.find(department => department.id === role.departmentId)?.name || role.departmentId} · {role.permissions.length} صلاحيات · {role.userCount} موظفين</span></span><span className="flex items-center gap-3"><Status active={role.active} /><ChevronDown size={16} /></span></summary><div className="mt-5 border-t pt-5"><RoleEditor role={role} departments={data.departments} action={props.saveRoleAction} canManage={editable} /></div></details>)}{!data.roles.length && <p className="rounded-xl bg-white p-8 text-center text-sm text-slate-500">لا توجد أدوار متاحة في هذه التهيئة.</p>}</div>}
    {section === 'users' && <div className="space-y-4"><form action="/admin/access-control" className="flex flex-wrap items-end gap-3"><input type="hidden" name="section" value="users" /><label className="min-w-48 flex-1 text-sm font-bold">بحث الموظف<input name="q" type="search" defaultValue={props.q} className={input} placeholder="الاسم أو اسم الدخول أو الرقم" /></label><button className={secondary}><Search size={16} /> بحث</button></form>{selectedUser && <section className="rounded-2xl border border-amber-200 bg-white p-5"><Assignment key={selectedUser.id} data={data} user={selectedUser} currentUserId={currentUserId} action={props.assignAction} canManage={editable} /></section>}<div className="grid gap-3 sm:grid-cols-2">{data.users.map(user => { const roleIds = data.assignments.find(assignment => assignment.userId === user.id)?.roleIds || []; return <Link key={user.id} href={`/admin/access-control?section=users&userId=${user.id}${props.q ? `&q=${encodeURIComponent(props.q)}` : ''}`} className={`rounded-xl border bg-white p-4 ${user.id === props.selectedUserId ? 'border-[#F0B429]' : 'border-slate-200'}`}><div className="flex items-center justify-between gap-2"><strong>{user.name || user.userName || `موظف #${user.id}`}</strong><Status active={user.enabled} /></div><p className="mt-1 text-xs text-slate-500">#{user.id}{user.id === currentUserId ? ' · حسابك الحالي' : ''}</p><div className="mt-3 flex flex-wrap gap-1.5">{roleIds.map(id => <span key={id} className="rounded-md bg-slate-100 px-2 py-1 text-xs">{data.roles.find(role => role.id === id)?.name || id}</span>)}{!roleIds.length && <span className="text-xs text-slate-500">لم تُسند أدوار</span>}</div></Link>; })}</div>{!data.users.length && <p className="rounded-xl bg-white p-8 text-center text-sm text-slate-500">لا يوجد موظف مطابق للبحث.</p>}</div>}
    {section === 'departments' && <div className="grid gap-4 md:grid-cols-2">{data.departments.map(department => <section key={department.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center justify-between gap-2"><h2 className="font-extrabold">{department.name}</h2><Status active={department.active} /></div><p className="mb-4 text-xs text-slate-500">{data.roles.filter(role => role.departmentId === department.id).length} أدوار مرتبطة. تعطيل القسم يوقف وصول أدواره.</p><form action={props.saveDepartmentAction} className="space-y-4"><input type="hidden" name="id" value={department.id} /><fieldset disabled={!editable} className="space-y-4"><label className="text-sm font-bold">اسم القسم<input name="name" required maxLength={120} defaultValue={department.name} className={input} /></label><label className="flex items-center gap-2 text-sm"><input name="active" type="checkbox" value="1" defaultChecked={department.active} className="h-4 w-4 accent-[#16294A]" /> القسم نشط</label><Reason /></fieldset><Submit disabled={!editable}>حفظ القسم</Submit></form></section>)}{editable && <section className="rounded-2xl border border-dashed border-amber-400 bg-white p-5"><h2 className="mb-4 font-extrabold">إضافة قسم</h2><form action={props.saveDepartmentAction} className="space-y-4"><label className="text-sm font-bold">اسم القسم<input name="name" required maxLength={120} className={input} /></label><input type="hidden" name="active" value="1" /><Reason /><Submit>إنشاء القسم</Submit></form></section>}</div>}
    {section === 'audit' && <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="p-5"><h2 className="font-extrabold">تاريخ كل تغيير</h2><p className="mt-1 text-xs text-slate-500">المستخدم والوقت والسبب والحالة قبل التغيير وبعده، مع مرجع الجلسة بدل بياناتها السرية.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-xs"><thead className="bg-slate-50"><tr>{['الوقت', 'المستخدم', 'الإجراء', 'السبب', 'التفاصيل'].map(label => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{data.audit.map(row => <tr key={row.id} className="border-t border-slate-100"><td className="p-3"><time dateTime={row.at}>{new Intl.DateTimeFormat('ar-SA', { dateStyle: 'medium', timeStyle: 'short', calendar: 'gregory', timeZone: 'Asia/Riyadh' }).format(new Date(row.at))}</time></td><td className="p-3">{row.actorId === null ? 'ترحيل النظام' : `#${row.actorId}`}</td><td className="p-3">{({ 'department.save': 'حفظ قسم', 'role.save': 'حفظ دور', 'user.roles': 'إسناد أدوار', initialize: 'تهيئة إدارة الوصول', 'account.state': 'تحديث حالة الحساب' } as Record<string, string>)[row.action] || row.action}<p className="mt-1 text-slate-500">{row.target}</p></td><td className="p-3">{row.reason}</td><td className="p-3"><details><summary className="cursor-pointer font-bold">قبل / بعد</summary><div className="mt-2 max-w-md space-y-2"><p>قبل:</p><pre className="whitespace-pre-wrap break-all rounded bg-slate-50 p-2" dir="ltr">{JSON.stringify(row.before, null, 2)}</pre><p>بعد:</p><pre className="whitespace-pre-wrap break-all rounded bg-slate-50 p-2" dir="ltr">{JSON.stringify(row.after, null, 2)}</pre><p className="break-all">عنوان الاتصال: <bdi>{row.ip || 'غير متاح'}</bdi></p><p className="break-all">بصمة الجلسة: <bdi>{row.sessionFingerprint || 'غير متاح'}</bdi></p></div></details></td></tr>)}</tbody></table></div>{!data.audit.length && <p className="p-8 text-center text-sm text-slate-500">لا توجد تغييرات مسجلة بعد.</p>}</section>}
    <footer className="flex items-center gap-2 border-t pt-4 text-xs text-slate-500"><Check size={14} />تُطبّق الصلاحيات من مصدر واحد على الصفحات والقوائم والإجراءات، ويُحفظ سبب كل تعديل.</footer>
  </main>;
}
