'use client';
import {useState} from 'react';
import {CATEGORY_KINDS,type CategoryKind,type SubcategoryOption} from '@/lib/ad-categories/contracts';
import type {CategoryField} from '@/lib/ad-categories/validation';
import {CATEGORY_SEED_TEMPLATES} from '@/lib/ad-categories/seed-templates';
import {nextCategoryFieldKey} from '@/lib/ad-categories/admin-input';
import {allowedPricingModes,defaultListingPolicy,LISTING_TYPE_KEYS,LISTING_TYPE_LABELS,PRICING_LABELS,type ListingPolicy,type ListingTypeKey} from '@/lib/ad-categories/listing-policy';
const input='w-full rounded-lg border border-primary/25 bg-white p-2 text-sm';
export function AdCategoryEditor({initial,categoryId,action}:{initial?:SubcategoryOption;categoryId:number;action:(fd:FormData)=>Promise<void>}){
  const [fields,setFields]=useState<CategoryField[]>(initial?.fields||[]);
  const [kind,setKind]=useState<CategoryKind>(initial?.kind||'other');
  const [listingPolicy,setListingPolicy]=useState<ListingPolicy>(initial?.listingPolicy??defaultListingPolicy(initial?.kind||'other'));
  const [price,setPrice]=useState(initial?.priceEnabled??false),[goods,setGoods]=useState(initial?.goodsEnabled??false);
  const [template,setTemplate]=useState('');
  const update=(i:number,patch:Partial<CategoryField>)=>setFields(fields.map((f,n)=>n===i?{...f,...patch}:f));
  return <form action={action} className="space-y-3 rounded-xl border p-3">
    {initial&&<input type="hidden" name="id" value={initial.id}/>}
    <input type="hidden" name="category_id" value={categoryId}/><input type="hidden" name="version" value={initial?.version??0}/><input type="hidden" name="fields_json" value={JSON.stringify(fields)}/><input type="hidden" name="listing_policy_json" value={JSON.stringify(listingPolicy)}/>
    <div className="grid gap-2 sm:grid-cols-3"><label>اسم القسم الفرعي<input name="name" className={input} required maxLength={200} defaultValue={initial?.name}/></label><label>الترتيب<input name="order" type="number" min={0} max={10000} className={input} defaultValue={initial?.order??0}/></label><label>النوع<select name="kind" className={input} value={kind} onChange={e=>{const next=e.target.value as CategoryKind;setKind(next);setListingPolicy(defaultListingPolicy(next));if(next==='jobs'){setPrice(false);setGoods(false);}}}>{CATEGORY_KINDS.map(k=><option key={k} value={k}>{({goods:'سلع',property:'عقارات',jobs:'وظائف',service:'خدمات',livestock:'مواشٍ',plants:'نباتات',other:'أخرى'})[k]}</option>)}</select></label></div>
    <div className="flex flex-wrap gap-4"><label><input type="checkbox" name="price_enabled" value="1" checked={kind!=='jobs'&&price} disabled={kind==='jobs'} onChange={e=>setPrice(e.target.checked)}/> إظهار السعر العام</label><label><input type="checkbox" name="goods_enabled" value="1" checked={kind!=='jobs'&&goods} disabled={kind==='jobs'} onChange={e=>setGoods(e.target.checked)}/> إظهار تفاصيل السلع العامة</label></div>
    <fieldset className="space-y-2 rounded-xl border border-amber-300 bg-amber-50/50 p-3"><legend className="px-2 font-bold">أنواع الإعلان والتسعير المسموح</legend>
      {listingPolicy.types.map((type,index)=><div key={type.key} className="rounded-lg border bg-white p-2"><div className="flex items-center gap-2"><strong>{LISTING_TYPE_LABELS[type.key]}</strong><input className={input} aria-label={`اسم ${type.key}`} value={type.label} onChange={e=>setListingPolicy({types:listingPolicy.types.map((item,i)=>i===index?{...item,label:e.target.value}:item)})}/>{listingPolicy.types.length>1&&<button type="button" className="text-red-700" onClick={()=>setListingPolicy({types:listingPolicy.types.filter((_,i)=>i!==index)})}>إزالة النوع</button>}</div><div className="mt-2 flex flex-wrap gap-3">{allowedPricingModes(type.key).map(mode=><label key={mode} className="text-sm"><input type="checkbox" checked={type.pricing.includes(mode)} onChange={e=>setListingPolicy({types:listingPolicy.types.map((item,i)=>i===index?{...item,pricing:e.target.checked?[...item.pricing,mode]:item.pricing.filter(value=>value!==mode)}:item)})}/> {PRICING_LABELS[mode]}</label>)}</div></div>)}
      <select aria-label="إضافة نوع إعلان" className={input} value="" onChange={e=>{const key=e.target.value as ListingTypeKey;if(key&&!listingPolicy.types.some(type=>type.key===key)){const modes=allowedPricingModes(key);setListingPolicy({types:[...listingPolicy.types,{key,label:LISTING_TYPE_LABELS[key],pricing:[modes[0]]}]});}}}><option value="">إضافة نوع إعلان…</option>{LISTING_TYPE_KEYS.filter(key=>!listingPolicy.types.some(type=>type.key===key)).map(key=><option key={key} value={key}>{LISTING_TYPE_LABELS[key]}</option>)}</select>
    </fieldset>
    <div className="flex flex-wrap gap-2"><select aria-label="قالب الحقول" className={input} value={template} onChange={e=>setTemplate(e.target.value)}><option value="">اختر قالباً اختيارياً</option>{CATEGORY_SEED_TEMPLATES.map(t=><option key={t.key} value={t.key}>{t.categoryName} — {t.name}</option>)}</select><button type="button" disabled={!template} className="rounded border px-3 py-2" onClick={()=>{const t=CATEGORY_SEED_TEMPLATES.find(t=>t.key===template);if(t){setFields(t.fields.map(f=>({...f,options:[...f.options]})));setKind(t.kind);setPrice(t.priceEnabled);setGoods(t.goodsEnabled);setListingPolicy(t.listingPolicy);}}}>استبدال الحقول والسياسة بالقالب المختار</button><p className="text-xs text-muted-foreground">لا يُطبّق على الإعلانات أو قاعدة البيانات حتى تحفظ هذا القسم الفرعي.</p></div>
    {fields.map((f,i)=><fieldset key={i} className="grid gap-2 rounded-lg border bg-primary/5 p-3 sm:grid-cols-3"><legend>حقل {i+1}</legend>
      <label>المعرف الثابت<input className={input} required pattern="[a-z][a-z0-9_]{0,47}" value={f.key} onChange={e=>update(i,{key:e.target.value})}/></label>
      <label>اسم الحقل<input className={input} required maxLength={120} value={f.label} onChange={e=>update(i,{label:e.target.value})}/></label>
      <label>النوع<select className={input} value={f.type} onChange={e=>update(i,{type:e.target.value as CategoryField['type']})}>{(['text','textarea','number','decimal','select','multiselect','radio','boolean','date','year','range'] as const).map(t=><option key={t} value={t}>{({text:'نص',textarea:'نص طويل',number:'رقم',decimal:'رقم عشري',select:'اختيار واحد',multiselect:'اختيارات متعددة',radio:'أزرار اختيار',boolean:'نعم / لا',date:'تاريخ',year:'سنة',range:'نطاق رقمي'})[t]}</option>)}</select></label>
      <label>المجموعة<input className={input} maxLength={100} value={f.group} onChange={e=>update(i,{group:e.target.value})}/></label>
      <label>الترتيب<input className={input} type="number" min={0} max={10000} value={f.order} onChange={e=>update(i,{order:Number(e.target.value)})}/></label>
      <label>الوحدة<input className={input} maxLength={30} value={f.unit||''} onChange={e=>update(i,{unit:e.target.value})}/></label>
      <label>النص داخل الحقل<input className={input} maxLength={160} value={f.placeholder||''} onChange={e=>update(i,{placeholder:e.target.value})}/></label>
      <label className="sm:col-span-2">مساعدة قصيرة<input className={input} maxLength={500} value={f.helpText||''} onChange={e=>update(i,{helpText:e.target.value})}/></label>
      {f.type==='number'&&(['min','max'] as const).map(k=><label key={k}>{k==='min'?'الحد الأدنى':'الحد الأعلى'}<input className={input} type="number" step="any" value={f[k]??''} onChange={e=>update(i,{[k]:e.target.value===''?undefined:Number(e.target.value)})}/></label>)}
      {(f.type==='select'||f.type==='multiselect'||f.type==='radio')&&<label className="sm:col-span-3">الخيارات — خيار بكل سطر<textarea className={input} required value={f.options.join('\n')} onChange={e=>update(i,{options:e.target.value.split('\n')})}/></label>}
      <label>يظهر عندما<select className={input} value={f.dependsOn||''} onChange={e=>update(i,e.target.value?{dependsOn:e.target.value,dependencyOperator:'equals',dependencyValue:''}:{dependsOn:undefined,dependencyOperator:undefined,dependencyValue:undefined})}><option value="">دائمًا</option><option value="listing_type">نوع الإعلان</option>{fields.filter((_,n)=>n!==i).map(option=><option key={option.key} value={option.key}>{option.label||option.key}</option>)}</select></label>
      {f.dependsOn&&<><label>المقارنة<select className={input} value={f.dependencyOperator||'equals'} onChange={e=>update(i,{dependencyOperator:e.target.value as CategoryField['dependencyOperator']})}><option value="equals">يساوي</option><option value="not_equals">لا يساوي</option><option value="in">ضمن قائمة</option><option value="not_in">ليس ضمن قائمة</option><option value="truthy">له قيمة</option></select></label><label>القيمة الشرطية<input className={input} value={Array.isArray(f.dependencyValue)?f.dependencyValue.join('\n'):String(f.dependencyValue??'')} onChange={e=>update(i,{dependencyValue:f.dependencyOperator==='in'||f.dependencyOperator==='not_in'?e.target.value.split('\n').filter(Boolean):e.target.value})}/></label></>}
      <div className="sm:col-span-3 flex flex-wrap gap-3"><label><input type="checkbox" checked={f.required} onChange={e=>update(i,{required:e.target.checked})}/> مطلوب عند الظهور</label><label><input type="checkbox" checked={f.visible} onChange={e=>update(i,{visible:e.target.checked})}/> نشط</label><label><input type="checkbox" checked={f.searchable===true} onChange={e=>update(i,{searchable:e.target.checked})}/> بحث</label><label><input type="checkbox" checked={f.filterable===true} onChange={e=>update(i,{filterable:e.target.checked})}/> فلتر</label><label><input type="checkbox" checked={f.comparable===true} onChange={e=>update(i,{comparable:e.target.checked})}/> مقارنة</label><label><input type="checkbox" checked={f.showInCard===true} onChange={e=>update(i,{showInCard:e.target.checked})}/> البطاقة</label><label><input type="checkbox" checked={f.showInDetails!==false} onChange={e=>update(i,{showInDetails:e.target.checked})}/> التفاصيل</label></div><button type="button" className="text-red-700" onClick={()=>setFields(fields.filter((_,n)=>n!==i))}>إزالة من التعريف (القيمة القديمة تبقى محفوظة)</button>
    </fieldset>)}
    <div className="flex gap-3"><button type="button" className="rounded border px-3 py-2" onClick={()=>setFields(current=>[...current,{key:nextCategoryFieldKey(current),label:'',type:'text',group:'',required:false,visible:true,order:current.length,options:[],searchable:false,filterable:false,comparable:false,showInCard:false,showInDetails:true}])}>إضافة حقل</button><button className="rounded bg-primary px-4 py-2 text-white">حفظ القسم الفرعي</button></div>
  </form>;
}
