'use client';
import {useState} from 'react';

type Result={url?:unknown;expiresAt?:unknown;generation?:unknown;status?:unknown;error?:unknown};
const primary='inline-flex min-h-11 items-center justify-center rounded-xl bg-[#16294A] px-4 py-2 text-sm font-bold text-white disabled:opacity-50';
const secondary='inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-bold text-[#16294A] disabled:opacity-50';
export function CopyOpenLink({url,openLabel,copyLabel}:{url:string;openLabel:string;copyLabel:string}){
 const [copied,setCopied]=useState(false);
 return <div className="flex flex-wrap gap-2"><a className={secondary} href={url} target="_blank" rel="noreferrer">{openLabel}</a><button type="button" className={secondary} onClick={async()=>{try{await navigator.clipboard.writeText(url);setCopied(true);}catch{setCopied(false);}}}>{copied?'تم النسخ':copyLabel}</button></div>;
}
export function SupplierDataLinkControls({supplierId,status,expiresAt}:{supplierId:string;status?:string;expiresAt?:string}){
 const [url,setUrl]=useState(''),[expiry,setExpiry]=useState(expiresAt||''),[current,setCurrent]=useState(status||''),[pending,setPending]=useState(false),[error,setError]=useState('');
 const action=async(mode:'issue'|'revoke')=>{if(pending)return;setPending(true);setError('');try{const body=new FormData();body.set('supplierId',supplierId);body.set('mode',mode);const response=await fetch('/api/suppliers/data-invite/admin',{method:'POST',body,credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'}});const result=await response.json() as Result;if(!response.ok)throw Error();if(mode==='issue'){if(typeof result.url!=='string'||typeof result.expiresAt!=='string')throw Error();const parsed=new URL(result.url);if(parsed.origin!==window.location.origin||!/^\/supplier\/data\/[A-Za-z0-9_-]{43}$/.test(parsed.pathname))throw Error();setUrl(result.url);setExpiry(result.expiresAt);setCurrent('open');}else{setUrl('');setExpiry('');setCurrent('revoked');}}catch{setError('تعذر تنفيذ العملية. أعد المحاولة.');}finally{setPending(false);}};
 if(current==='submitted')return <p className="text-sm font-bold text-amber-800">تم إيقاف تعديل الرابط مؤقتًا لأن البيانات بانتظار المراجعة.</p>;
 return <div className="space-y-3"><p className="text-sm">الحالة: <b>{current||'لم يصدر رابط'}</b>{expiry?` · ينتهي ${new Date(expiry).toLocaleString('ar-SA')}`:''}</p>{url&&<><label className="block text-xs font-bold">رابط بيانات المورد<input readOnly dir="ltr" className="mt-1 min-h-11 w-full rounded-lg border bg-white px-3 text-left text-xs" value={url}/></label><CopyOpenLink url={url} openLabel="فتح رابط البيانات" copyLabel="نسخ رابط البيانات"/></>}<div className="flex flex-wrap gap-2"><button type="button" disabled={pending} className={primary} onClick={()=>action('issue')}>{current&&current!=='revoked'?'إعادة إصدار الرابط':'إنشاء رابط بيانات المورد'}</button>{current&&current!=='revoked'&&<button type="button" disabled={pending} className={secondary} onClick={()=>action('revoke')}>إلغاء الرابط</button>}</div>{error&&<p role="alert" className="text-sm font-bold text-red-700">{error}</p>}<p className="text-xs leading-6 text-slate-500">إعادة الإصدار تلغي الرابط السابق فورًا. حفاظًا على الأمان لا يمكن استرجاع نص الرابط بعد مغادرة الصفحة؛ أعد إصداره إذا فقدته.</p></div>;
}
