import {ONBOARDING_FIELDS,maskedOnboardingValue,type OnboardingValues} from '@/lib/suppliers/onboarding-fields';
import {SupplierDataLinkControls,CopyOpenLink} from './supplier-data-link-controls';
import {SupplierOwnerInviteButton} from './supplier-owner-invite-button';

type Invitation={status:string;generation:number;expiresAt:string;values:OnboardingValues};
type Action=(form:FormData)=>void|Promise<void>;
export function SupplierDataInvitePanel({supplierId,supplierName,invitation,approvedStoreUrl,connected,approveAction,reopenAction}:{supplierId:string;supplierName:string;invitation:Invitation|null;approvedStoreUrl:string|null;connected:boolean;approveAction:Action;reopenAction:Action}){
 const submitted=invitation?.status==='submitted';
 return <section className="mt-5 space-y-4 rounded-2xl border border-blue-200 bg-blue-50 p-4" aria-label={`بيانات وربط ${supplierName}`}><div><h3 className="font-black text-[#16294A]">رابط بيانات المورد</h3><p className="mt-1 text-sm leading-7 text-slate-700">أرسل رابطًا فريدًا لصاحب المتجر ليحفظ البيانات ويرسلها للمراجعة دون دخول إلى لوحة الإدارة.</p></div><SupplierDataLinkControls supplierId={supplierId} status={invitation?.status} expiresAt={invitation?.expiresAt}/>
 {submitted&&<section className="rounded-xl border-2 border-amber-300 bg-white p-4"><h4 className="font-black text-amber-900">بانتظار المراجعة</h4><dl className="mt-3 grid gap-3 sm:grid-cols-2">{ONBOARDING_FIELDS.filter(([key])=>invitation.values[key]).map(([key,label])=><div key={key} className="rounded-lg bg-slate-50 p-3"><dt className="text-xs font-bold text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm font-semibold">{maskedOnboardingValue(key,invitation.values[key])}</dd></div>)}</dl><div className="mt-4 flex flex-wrap gap-3"><form action={approveAction}><input type="hidden" name="supplierId" value={supplierId}/><input type="hidden" name="generation" value={invitation.generation}/><button className="rounded-xl bg-emerald-700 px-4 py-3 font-bold text-white">اعتماد بيانات المورد</button></form><form action={reopenAction}><input type="hidden" name="supplierId" value={supplierId}/><input type="hidden" name="generation" value={invitation.generation}/><button className="rounded-xl border border-amber-400 bg-white px-4 py-3 font-bold text-amber-900">إعادة للمورد للتصحيح</button></form></div></section>}
 {approvedStoreUrl&&<section className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><h4 className="font-black text-emerald-950">روابط المتجر بعد الاعتماد</h4><p dir="ltr" className="my-3 break-all rounded-lg bg-white p-3 text-left text-sm">{approvedStoreUrl}</p><CopyOpenLink url={approvedStoreUrl} openLabel="فتح رابط المتجر" copyLabel="نسخ رابط المتجر"/>{connected?<p className="mt-4 font-bold text-emerald-800">متصل بسلة بالفعل — لا يحتاج رابط تفويض جديد.</p>:<div className="mt-4"><SupplierOwnerInviteButton supplierId={supplierId} supplierName={supplierName}/></div>}</section>}
 </section>;
}
