import Link from 'next/link';
import { requireAction } from '@/lib/roles';
import { prisma } from '@/lib/prisma';
import { categoryOptions, categoryLabels, categoriesOn } from '@/lib/categories-v2';
import { saveCategorySettings, initializeCategories, saveCategory, saveBranch, saveField, archiveField, restoreField } from './actions';
const input='rounded-lg border bg-white p-2 text-sm text-slate-900';
const button='rounded-lg bg-primary px-4 py-2 text-sm text-white';
export default async function CategoriesAdmin(){
  await requireAction('categories','view');
  const [cats,labels,on,fields]=await Promise.all([categoryOptions(),categoryLabels(),categoriesOn(),prisma.category_field_defs.findMany({orderBy:{ordered:'asc'}})]);
  return <div className="space-y-6"><header><h1 className="text-2xl font-bold">الأقسام والحقول المتخصصة</h1><p className="mt-2 text-sm text-slate-600">إخفاء القسم يمنع الإعلانات الجديدة فقط. الإعلانات السابقة وبياناتها تبقى محفوظة وظاهرة.</p><Link href="/admin/categories/review" className="mt-3 inline-block text-primary underline">مراجعة التصنيف والتحويل الجماعي ←</Link></header>
    <form action={saveCategorySettings} className="grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-2"><label><input name="enabled" type="checkbox" defaultChecked={on}/> إظهار نظام الأقسام للزوار والأعضاء</label>{[['title',labels.title,'عنوان الأقسام'],['intro',labels.intro,'الوصف'],['category_label',labels.category,'عنوان القسم'],['branch_label',labels.branch,'عنوان الفرع'],['details_label',labels.details,'عنوان المواصفات']].map(([key,value,label])=><label key={key} className="grid gap-1 text-sm">{label}<input name={key} defaultValue={value} className={input}/></label>)}<button className={button}>حفظ إعدادات العرض</button></form>
    <div className="flex flex-wrap gap-4"><form action={initializeCategories}><button className={button}>إضافة الأقسام والفروع الأولية الناقصة</button></form><Link className="p-2 text-primary underline" href="/categories">معاينة الأقسام</Link></div>
    <form action={saveCategory} className="flex flex-wrap gap-3 rounded-xl border p-4"><input name="id" type="hidden" value="0"/><input required name="name" placeholder="اسم قسم جديد" aria-label="اسم قسم جديد" className={input}/><input name="ordered" type="number" min="0" defaultValue="0" aria-label="ترتيب القسم" className={input}/><label><input name="active" type="checkbox" defaultChecked/> فعال</label><button className={button}>إضافة قسم</button></form>
    {cats.map(cat=><details key={cat.id} className="rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-bold">{cat.name} · {cat.active?'فعال':'مخفي عن النشر الجديد'} · {cat.branches.length} فروع</summary><div className="mt-4 space-y-4">
      <form action={saveCategory} className="flex flex-wrap gap-2"><input type="hidden" name="id" value={cat.id}/><input name="name" defaultValue={cat.name} required className={input} aria-label="اسم القسم"/><input name="ordered" type="number" min="0" defaultValue={0} className={input} aria-label="الترتيب"/><label><input type="checkbox" name="active" defaultChecked={cat.active}/> تفعيل القسم</label><button className={button}>حفظ القسم</button></form>
      <h2 className="font-bold">الفروع</h2>{[...cat.branches,{id:0,name:'',active:true}].map(sub=><form key={sub.id} action={saveBranch} className="flex flex-wrap items-center gap-2"><input type="hidden" name="id" value={sub.id}/><input type="hidden" name="categoryId" value={cat.id}/><input required name="name" defaultValue={sub.name} placeholder="فرع جديد" aria-label="اسم الفرع" className={input}/><input name="ordered" type="number" min="0" defaultValue={0} aria-label="ترتيب الفرع" className={input}/><label><input name="active" type="checkbox" defaultChecked={sub.active}/> فعال</label><button className={button}>{sub.id?'حفظ':'إضافة فرع'}</button></form>)}
      <h2 className="font-bold">الحقول</h2>{[...fields.filter(f=>Number(f.category_id)===cat.id),{id:0n,field_key:'',label:'',field_type:'text',options:'',required:0,active:1,ordered:0,subcategory_id:null,unit:null,searchable:0,visibility_rule:null}].map(field=><div key={String(field.id)} className={`rounded-xl border p-3 ${field.active===0?'bg-slate-100 opacity-70':'bg-slate-50'}`}><form action={saveField} className="grid gap-2 sm:grid-cols-2"><input type="hidden" name="id" value={String(field.id)}/><input type="hidden" name="categoryId" value={cat.id}/><input name="key" defaultValue={field.field_key} readOnly={field.id!==0n} required pattern="[a-z][a-z0-9_]{0,63}" placeholder="field_key" aria-label="مفتاح الحقل" className={input}/><input name="label" defaultValue={field.label} required placeholder="عنوان الحقل" aria-label="عنوان الحقل" className={input}/><select name="subcategoryId" defaultValue={String(field.subcategory_id||0)} className={input}><option value="0">مشترك في القسم</option>{cat.branches.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select name="type" defaultValue={field.field_type} className={input} aria-label="نوع الحقل"><option value="text">نص</option><option value="number">رقم</option><option value="select">اختيارات</option></select><input name="unit" defaultValue={field.unit||''} placeholder="الوحدة: متر، ريال، كم" className={input}/><input name="options" defaultValue={field.options||''} placeholder="اختيار أول|اختيار ثان" aria-label="الاختيارات مفصولة بعلامة |" className={input}/><input name="visibilityField" placeholder="مفتاح شرط الظهور" className={input}/><input name="visibilityValue" placeholder="قيمة شرط الظهور" className={input}/><label><input type="checkbox" name="required" defaultChecked={field.required===1}/> إجباري</label><label><input type="checkbox" name="searchable" defaultChecked={field.searchable===1}/> يستخدم في البحث</label><label><input type="checkbox" name="active" defaultChecked={field.active===1}/> ظاهر</label><input name="ordered" type="number" min="0" defaultValue={field.ordered} aria-label="ترتيب الحقل" className={input}/><button className={button}>{field.id?'حفظ الحقل':'إضافة حقل'}</button></form>{field.id!==0n&&(field.active===0?<form action={restoreField} className="mt-2"><input type="hidden" name="id" value={String(field.id)}/><button className="rounded-lg border border-emerald-300 px-3 py-1 text-xs text-emerald-700">استعادة الحقل</button></form>:<form action={archiveField} className="mt-2"><input type="hidden" name="id" value={String(field.id)}/><button className="rounded-lg border border-red-300 px-3 py-1 text-xs text-red-700">إخفاء وأرشفة الحقل</button></form>)}</div>)}
    </div></details>)}
  </div>;
}
