import Link from 'next/link';
import {CategoryAdminFilters} from '@/components/category-admin-filters';
import {notFound} from 'next/navigation';
import {getCategoryFormConfig} from '@/lib/ad-categories/service';
import {prisma} from '@/lib/prisma';
import {CategoryAdminNavigation} from '@/components/category-admin-navigation';
import {AdCategoryEditor} from '@/components/ad-category-editor';
import {CATEGORY_ADMIN_PAGES,categoryAdminQuery,type CategoryAdminQuery,type CategoryAdminView} from '@/lib/ad-categories/admin-navigation';
import {CATEGORY_EDITOR_SECTIONS,categoryEditorPath,isCategoryEditorSection} from '@/lib/ad-categories/admin-presentation';
import {saveCategory,saveCategorySettings,saveSubcategory,toggleCategory} from './actions';
const input='min-h-11 w-full min-w-0 rounded-lg border bg-white p-2 text-sm';
const button='inline-flex min-h-11 items-center justify-center rounded-lg border px-3 py-2 text-sm font-medium';
const labelNames:Record<string,string>={section:'عنوان مجموعة التصنيف',category:'اسم خانة القسم',subcategory:'اسم خانة القسم الفرعي',choose:'عبارة الاختيار',error:'رسالة خطأ التصنيف',details:'عنوان مواصفات الإعلان',preserve:'خيار إبقاء التصنيف الحالي',reclassify:'خيار تغيير التصنيف',preserveHint:'شرح إبقاء التصنيف',browse:'زر عرض الإعلانات',clear:'زر مسح التصفية',resultsTitle:'عنوان نتائج القسم',emptyText:'رسالة عدم وجود إعلانات'};
export async function CategoryAdminWorkspace({view,query:q}:{view:CategoryAdminView;query:CategoryAdminQuery}){
  const cfg=await getCategoryFormConfig(true),filter=categoryAdminQuery(q);
  if(filter.invalid)notFound();
  if(filter.category&&!cfg.categories.some(c=>c.id===filter.category))notFound();
  if(filter.subcategory&&!cfg.subcategories.some(s=>s.id===filter.subcategory&&(!filter.category||s.categoryId===filter.category)))notFound();
  if(view==='create'&&!filter.category)notFound();
  const categories=cfg.categories.filter(c=>!filter.category||c.id===filter.category);
  const title=view==='create'?'إضافة قسم فرعي':CATEGORY_ADMIN_PAGES[view].title;
  const ads=view==='ads'?await prisma.ads.findMany({where:{...(filter.category?{category_id:BigInt(filter.category)}:{}),...(filter.subcategory?{subcategory_id:filter.subcategory}:{}),...(q.review==='1'?{OR:[{cat_reviewed:0},{subcategory_id:null}]}:{})},select:{id:true,title:true,category_id:true,subcategory_id:true},orderBy:{id:'desc'},take:26,skip:(filter.page-1)*25}):[];
  const pageLink=(page:number)=>{const p=new URLSearchParams({page:String(page)});if(filter.category)p.set('category',String(filter.category));if(filter.subcategory)p.set('subcategory',String(filter.subcategory));if(q.review==='1')p.set('review','1');return `/admin/categories/ads?${p}`;};
  return <div dir="rtl" className="min-w-0 space-y-4">
    <h1 className="text-xl font-bold">{title}</h1><CategoryAdminNavigation current={view}/>
    {q.error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm">{q.error==='read-only'?'هذه معاينة محمية؛ لا يمكن حفظ تعديل البيانات هنا.':'لم يتم الحفظ. راجع المدخلات أو أعد تحميل الصفحة إذا تغيّر التعريف.'}</p>}
    {q.saved&&<p role="status" className="rounded-lg bg-emerald-50 p-3">{q.saved==='preview'?'تم تحديث الظهور في المعاينة فقط — قاعدة الإنتاج لم تتغير.':'تم الحفظ'}</p>}
    {(view==='ads'||view==='fields')&&<CategoryAdminFilters key={`${view}:${filter.category}:${filter.subcategory}`} view={view} categories={cfg.categories} subcategories={cfg.subcategories.map(({id,name,categoryId})=>({id,name,categoryId}))} initialCategory={filter.category} initialSubcategory={filter.subcategory} review={q.review==='1'}/>}
    {view==='manage'&&<section className="space-y-3 rounded-xl border p-3"><h2 className="font-bold">إضافة قسم رئيسي</h2><form action={saveCategory} className="grid min-w-0 gap-3 sm:grid-cols-3"><label>اسم القسم الجديد<input className={input} name="name" maxLength={200} required/></label><label>ترتيب العرض<input className={input} name="order" type="number" min={0} max={10000} defaultValue={0}/></label><button className={`${button} bg-primary text-white`}>إضافة قسم مخفي</button></form></section>}
    {(view==='manage'||view==='fields')&&categories.map(c=><details key={c.id} className="min-w-0 space-y-3 rounded-xl border p-3" open={Boolean(filter.category)}><summary className="min-h-11 cursor-pointer break-words font-bold">{c.name} — {c.active?'ظاهر':'مخفي'}</summary>
      {view==='manage'&&<><form action={saveCategory} className="grid min-w-0 gap-3 sm:grid-cols-3"><input type="hidden" name="id" value={c.id}/><label>اسم القسم<input className={input} name="name" maxLength={200} required defaultValue={c.name}/></label><label>ترتيب العرض<input className={input} name="order" type="number" min={0} max={10000} defaultValue={c.order}/></label><button className={button}>حفظ القسم</button></form><form action={toggleCategory}><input type="hidden" name="id" value={c.id}/><input type="hidden" name="active" value={c.active?'0':'1'}/><button className={button}>{c.active?'إخفاء القسم':'إظهار القسم'}</button></form><Link href={`/admin/categories/create?category=${c.id}`} className={button}>إضافة قسم فرعي مخفي</Link></>}
      {cfg.subcategories.filter(s=>s.categoryId===c.id).map(s=><section key={s.id} className="min-w-0 space-y-2 rounded-lg border bg-slate-50 p-3"><h2 className="break-words font-bold">{s.name} — {s.active?'ظاهر':'مخفي'}</h2>
        {view==='fields'?<nav aria-label={`إدارة حقول ${s.name}`} className="grid min-w-0 gap-2 sm:grid-cols-3">{Object.entries(CATEGORY_EDITOR_SECTIONS).map(([key,label])=>isCategoryEditorSection(key)&&<Link key={key} className={button} href={categoryEditorPath(s.id,key)}>{label}</Link>)}</nav>:<div className="grid gap-2 sm:grid-cols-3"><Link className={button} href={categoryEditorPath(s.id,'fields')}>تعديل القسم الفرعي وحقوله</Link><Link className={button} href={`/admin/categories/ads?category=${c.id}&subcategory=${s.id}`}>إعلانات هذا القسم</Link><form action={toggleCategory}><input type="hidden" name="sub" value="1"/><input type="hidden" name="id" value={s.id}/><input type="hidden" name="active" value={s.active?'0':'1'}/><button className={`${button} w-full`}>{s.active?'إخفاء القسم الفرعي':'إظهار القسم الفرعي'}</button></form></div>}
      </section>)}
      {!cfg.subcategories.some(s=>s.categoryId===c.id)&&<p className="text-sm">لا توجد أقسام فرعية بعد. أضفها من صفحة التحكم بالأقسام.</p>}
    </details>)}
    {view==='create'&&<><p>سيُضاف القسم الفرعي إلى: <strong>{categories[0]?.name}</strong>، ويبدأ مخفيًا حتى تُظهره من صفحة التحكم بالأقسام.</p><AdCategoryEditor categoryId={filter.category!} action={saveSubcategory}/></>}
    {view==='ads'&&<section aria-label="قائمة إعلانات الأقسام" className="space-y-3"><p className="text-sm">عرض إداري فقط؛ لا يُغيّر التصنيف أو بيانات الإعلانات.</p>{ads.slice(0,25).map(ad=><article key={String(ad.id)} className="min-w-0 space-y-2 rounded-xl border p-3"><h2 className="break-words font-bold">{ad.title||'إعلان بلا عنوان'}</h2><p className="break-words text-sm">#{String(ad.id)} · {cfg.categories.find(c=>c.id===Number(ad.category_id))?.name||'قسم غير متاح'} · {cfg.subcategories.find(s=>s.id===ad.subcategory_id)?.name||'بدون قسم فرعي'}</p><Link className={button} href={`/ads/${ad.id}`}>فتح الإعلان</Link></article>)}{ads.length===0&&<p>لا توجد إعلانات مطابقة لهذه التصفية.</p>}<nav aria-label="صفحات الإعلانات" className="flex flex-wrap gap-2">{filter.page>1&&<Link className={button} href={pageLink(filter.page-1)}>السابق</Link>}{ads.length>25&&<Link className={button} href={pageLink(filter.page+1)}>التالي</Link>}</nav></section>}
    {view==='settings'&&<><section className="rounded-xl border p-3"><h2 className="font-bold">تغطية تعريفات الأقسام</h2><p>{cfg.subcategories.filter(s=>s.version>0).length} قسمًا فرعيًا له تعريف حقول.</p>{cfg.subcategories.filter(s=>s.active&&s.version<1).map(s=><p key={s.id}>يحتاج تعريف حقول: {s.name}</p>)}</section><form action={saveCategorySettings} className="space-y-4 rounded-xl border p-3"><label className="flex min-h-11 items-center gap-2"><input type="checkbox" name="enabled" value="1" defaultChecked={cfg.enabled}/> تفعيل الأقسام في الإعلانات الفعلية</label><label className="flex min-h-11 items-start gap-2"><input type="checkbox" name="latest_templates" value="1" defaultChecked={cfg.useLatestTemplates!==false}/><span>استخدام أحدث القوالب النظامية للأقسام غير المعدلة<small className="block">لا يغيّر أقسامًا عدّلتها الإدارة.</small></span></label><div className="grid min-w-0 gap-3 sm:grid-cols-2">{Object.entries(cfg.labels).map(([key,value])=><label key={key}>{labelNames[key]||key}<input className={input} name={`label_${key}`} defaultValue={value} maxLength={500}/></label>)}</div><button className={`${button} bg-primary text-white`}>حفظ الإعدادات والنصوص</button></form></>}
  </div>;
}
