// Run against the isolated local V2 preview: node tests/browser-fields.mjs
// Optional PLAYWRIGHT_MODULE points to an already installed Playwright package.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import { catalog, visibleFields } from '../lib/category-fields.ts';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({channel:process.env.BROWSER_CHANNEL || 'msedge',headless:true});
const page = await browser.newPage({viewport:{width:1440,height:1100}});
const failures = [];
page.on('pageerror', error => failures.push(error.message));
const origin = process.env.PREVIEW_URL || 'http://127.0.0.1:4186';
assert.match(origin, /^http:\/\/(127\.0\.0\.1|localhost):\d+$/);
const output = process.env.QA_OUTPUT || 'test-results';
await mkdir(output,{recursive:true});
async function fresh() {
  await page.goto(`${origin}/ads/new/`);
  await page.evaluate(() => {localStorage.removeItem('trbhh-v2-ad-draft-v1');localStorage.removeItem('trbhh-v2-field-settings-v1');});
  await page.reload();
  await page.getByLabel('القسم الرئيسي').waitFor();
}
async function selectBranch(category, branch) {
  await page.getByLabel('القسم الرئيسي').selectOption(category);
  await page.getByLabel('التصنيف الفرعي').selectOption(branch);
  await page.locator('.category-details').waitFor();
}
try {
  await fresh();
  let count=0;
  for(const [category,branches] of Object.entries(catalog)) for(const [branch,profile] of Object.entries(branches)) {
    await selectBranch(category,branch);
    assert.equal(await page.locator('.category-details [id^="detail-"]:not([id$="-error"])').count(),visibleFields(profile,{}).length,`${category}/${branch}`);
    assert.equal(await page.getByRole('button',{name:'مستعمل',exact:true}).count(),profile.condition?1:0);
    assert.equal(await page.locator('.seller-money-input').count(),profile.pricing==='salary'?0:1);
    await page.getByRole('button',{name:'تغيير الفرع',exact:true}).click();
    count++;
  }
  console.log(`PASS: all ${count} leaf forms render correct fields, condition and price policy`);
  await selectBranch('عقارات','فلل ومنازل');
  await page.locator('#detail-purpose').selectOption('للإيجار');
  await page.locator('#detail-rentPeriod').selectOption('شهري');
  await page.locator('#detail-plotArea').fill('٦٠٠');
  await page.locator('#detail-district').pressSequentially('حي النخيل');
  assert.equal(await page.locator('#detail-district').inputValue(),'حي النخيل');
  await page.screenshot({path:`${output}/villa-fields.png`,fullPage:true});
  await page.locator('#detail-purpose').selectOption('للبيع');
  assert.equal(await page.locator('#detail-rentPeriod').count(),0);
  await page.getByRole('button',{name:'تغيير الفرع',exact:true}).click();
  await selectBranch('عقارات','أراضٍ');
  assert.equal(await page.locator('#detail-plotArea').inputValue(),'');
  assert.equal(await page.locator('#detail-bedrooms').count(),0);
  await page.screenshot({path:`${output}/land-fields.png`,fullPage:true});
  await page.getByRole('button',{name:'تغيير الفرع',exact:true}).click();
  await selectBranch('سيارات','سيارات');
  await page.locator('#detail-fuel').selectOption('كهرباء');
  assert.equal(await page.locator('#detail-range').count(),1);
  await page.locator('#detail-range').fill('450');
  await page.locator('#detail-fuel').selectOption('بنزين');
  assert.equal(await page.locator('#detail-range').count(),0);
  await page.getByRole('button',{name:'تغيير الفرع',exact:true}).click();
  await selectBranch('سيارات','قطع غيار');
  assert.equal(await page.locator('#detail-mileage').count(),0);
  await page.getByRole('button',{name:'تغيير الفرع',exact:true}).click();
  await selectBranch('وظائف','دوام كامل');
  await page.getByLabel('عنوان الإعلان').fill('محاسب لشركة تجريبية في الرياض');
  await page.getByLabel('وصف الإعلان').fill('وظيفة محاسب لمراجعة الحسابات والتقارير المالية. هذا إعلان تجريبي لا يمثل وظيفة متاحة.');
  await page.getByRole('combobox',{name:/^المنطقة/}).selectOption('الرياض');
  await page.getByRole('combobox',{name:/^المدينة/}).selectOption('الرياض');
  await page.locator('#detail-jobTitle').fill('محاسب مالي');
  await page.locator('#detail-workMode').selectOption('حضوري');
  await page.locator('#detail-qualification').selectOption('بكالوريوس');
  await page.locator('#detail-salaryMin').fill('٩٠٠٠');
  await page.locator('#detail-salaryMax').fill('٥٠٠٠');
  await page.getByRole('button',{name:'نشر تجريبي',exact:true}).click();
  assert.match(await page.locator('#detail-salaryMax-error').innerText(),/الحد الأعلى/);
  await page.locator('#detail-salaryMax').fill('١٢٠٠٠');
  await page.locator('#detail-salaryPeriod').selectOption('شهري');
  // Wait on an observed persistence condition, not an arbitrary sleep.
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('trbhh-v2-ad-draft-v1')||'null')?.form.details.salaryPeriod==='شهري');
  await page.reload();
  assert.equal(await page.locator('#detail-jobTitle').inputValue(),'محاسب مالي');
  assert.equal(await page.locator('#detail-salaryMin').inputValue(),'9000');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),true,'mobile overflow');
  await page.screenshot({path:`${output}/jobs-mobile.png`,fullPage:true});
  const review = await page.locator('.seller-ad-preview').innerText();
  assert.match(review,/9,000 – 12,000 ر.س \/ شهري/);
  assert.ok(!review.includes('جديد') && !review.includes('مستعمل') && !review.includes('المهارات المطلوبة'));
  await page.screenshot({path:`${output}/jobs-review.png`,fullPage:true});
  await page.getByRole('button',{name:'نشر تجريبي',exact:true}).click();
  await page.getByRole('heading',{name:'إعلانك التجريبي جاهز'}).waitFor();
  const id=await page.evaluate(() => JSON.parse(localStorage.getItem('trbhh-v2-seller-ads-v1'))[0].id);
  await page.goto(`${origin}/ads/new/?edit=${id}`);
  assert.equal(await page.locator('#detail-salaryMin').inputValue(),'9000');
  console.log('PASS: conditional fields, switching, Arabic numbers, validation, draft reload, mobile, publish and edit');
  await page.goto(`${origin}/field-settings/`);
  await page.getByRole('button',{name:'حفظ إعدادات الحقول',exact:true}).waitFor({state:'visible'});
  await page.getByLabel('اسم الحقل الجديد',{exact:true}).fill('تقرير فحص التربة');
  await page.getByRole('button',{name:'إضافة الحقل',exact:true}).click();
  await page.locator('.category-admin-row').filter({has:page.getByLabel('اسم تقرير فحص التربة',{exact:true})}).getByLabel('إجباري',{exact:true}).check();
  await page.getByRole('button',{name:'حفظ إعدادات الحقول',exact:true}).click();
  await page.getByText('حُفظت إعدادات الحقول في هذا المتصفح فقط.').waitFor();
  await page.goto(`${origin}/ads/new/`);
  await page.locator('#ad-classification').waitFor();
  assert.equal(await page.locator('.ad-page-section').count(),4);
  if (await page.getByRole('button',{name:'تغيير الفرع',exact:true}).count()) await page.getByRole('button',{name:'تغيير الفرع',exact:true}).click();
  await selectBranch('عقارات','أراضٍ');
  assert.equal(await page.getByLabel('تقرير فحص التربة').getAttribute('aria-required'),'true');
  await page.getByRole('button',{name:'تغيير الفرع',exact:true}).click();
  await selectBranch('عقارات','شقق');
  assert.equal(await page.getByLabel('تقرير فحص التربة').count(),0);
  console.log('PASS: local field settings apply only to the selected branch');
  await page.goto(`${origin}/field-settings/`);
  const landOptions=page.locator('.category-admin-row').filter({has:page.getByLabel('اسم استخدام الأرض',{exact:true})}).getByLabel('الخيارات — افصل بينها بعلامة |');
  await landOptions.fill(' | ');
  await page.getByRole('button',{name:'حفظ إعدادات الحقول',exact:true}).click();
  await page.getByText('أضف خياراً صالحاً واحداً على الأقل لحقل استخدام الأرض.').waitFor();
  assert.equal(await page.locator('.category-admin-row').filter({has:page.getByLabel('اسم الغرض من الإعلان',{exact:true})}).locator('input[disabled]').count(),1);
  // Seed isolated fixtures to test status writes across ads after a catalog option changes.
  await page.evaluate(() => {
    const old=JSON.parse(localStorage.getItem('trbhh-v2-seller-ads-v1'))[0];
    const land={...old,id:'local-preservation-a',category:'عقارات',subcategory:'أراضٍ',title:'أرض تجريبية محفوظة',price:'100000',condition:'',details:{purpose:'للبيع',plotArea:'600',landUse:'تجاري',terrain:'مستوية',district:'النخيل',utilities:['كهرباء']}};
    localStorage.setItem('trbhh-v2-seller-ads-v1',JSON.stringify([land,{...old,id:'local-preservation-b',title:'تجربة حالة إعلان آخر'}]));
    localStorage.setItem('trbhh-v2-field-settings-v1',JSON.stringify({'عقارات/أراضٍ':{fields:{district:{hidden:true},landUse:{options:['سكني']},utilities:{options:['مياه']}}}}));
    localStorage.removeItem('trbhh-v2-ad-draft-v1');
  });
  await page.goto(`${origin}/seller/`);
  await page.getByRole('button',{name:'إيقاف تجربة حالة إعلان آخر',exact:true}).click();
  const afterStatus=await page.evaluate(() => JSON.parse(localStorage.getItem('trbhh-v2-seller-ads-v1')).find(ad=>ad.id==='local-preservation-a').details);
  assert.equal(afterStatus.landUse,'تجاري');assert.equal(afterStatus.district,'النخيل');
  await page.goto(`${origin}/ads/new/?edit=local-preservation-a`);
  assert.equal(await page.locator('#detail-district').count(),0);
  assert.equal(await page.locator('#detail-landUse').inputValue(),'تجاري');
  await page.getByRole('button',{name:'حفظ التعديلات التجريبية',exact:true}).click();
  await page.locator('#detail-landUse-error').waitFor();
  assert.equal(await page.getByRole('button',{name:'إزالة الخيارات غير المتاحة من الخدمات المتوفرة',exact:true}).count(),1,'retired multi-select needs a removal control');
  await page.getByRole('button',{name:'إزالة الخيارات غير المتاحة من الخدمات المتوفرة',exact:true}).click();
  await page.locator('#detail-landUse').selectOption('سكني');
  await page.locator('#detail-plotArea').fill('650');
  await page.getByRole('button',{name:'حفظ التعديلات التجريبية',exact:true}).click();
  await page.getByRole('heading',{name:'حُفظت تعديلات إعلانك'}).waitFor();
  const afterEdit=await page.evaluate(() => JSON.parse(localStorage.getItem('trbhh-v2-seller-ads-v1')).find(ad=>ad.id==='local-preservation-a').details);
  assert.equal(afterEdit.district,'النخيل');assert.equal(afterEdit.plotArea,'650');assert.equal(afterEdit.landUse,'سكني');
  assert.deepEqual(afterEdit.utilities,[]);
  console.log('PASS: empty options blocked, rule options protected, retired selections survive status writes, archived values survive editing');
  assert.deepEqual(failures,[],'browser runtime errors');
  console.log('PASS: no browser runtime errors');
} catch(error) {
  console.error('URL:',page.url(),'Headings:',await page.locator('h1,h2').allTextContents());
  await page.screenshot({path:`${output}/failure.png`,fullPage:true});
  throw error;
} finally { await browser.close(); }
