import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const origin=process.env.PREVIEW_URL || 'http://127.0.0.1:4187';
assert.match(origin,/^http:\/\/(127\.0\.0\.1|localhost):\d+$/);
const output=process.env.QA_OUTPUT || 'test-results';
await mkdir(output,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(origin+'/field-settings/');
 await page.getByLabel('اسم الحقل الجديد',{exact:true}).fill('خيارات الفحص');
 await page.getByLabel('نوع الحقل',{exact:true}).selectOption('multi');
 await page.getByLabel('الخيار 1',{exact:true}).fill('تقرير هندسي');
 await page.getByLabel('الخيار 2',{exact:true}).fill('فحص تربة');
 await page.getByRole('button',{name:'إضافة خيار',exact:true}).click();
 await page.getByLabel('الخيار 3',{exact:true}).fill('خيار محذوف');
 await page.getByRole('button',{name:'حذف الخيار 3',exact:true}).click();
 await page.getByLabel('الحقل الجديد إجباري',{exact:true}).check();
 await page.getByRole('button',{name:'إضافة الحقل',exact:true}).click();
 await page.getByRole('button',{name:'حفظ إعدادات الحقول',exact:true}).click();
 await page.goto(origin+'/ads/new/');
 await page.getByRole('button',{name:'عقارات',exact:true}).click();
 await page.getByLabel('التصنيف الفرعي').selectOption('أراضٍ');
 await page.getByRole('button',{name:'نشر تجريبي',exact:true}).click();
 await page.getByText('أكمل حقل خيارات الفحص.',{exact:true}).last().waitFor();
 await page.getByLabel('تقرير هندسي',{exact:true}).check();
 await page.getByLabel('فحص تربة',{exact:true}).check();
 assert.match(await page.locator('.seller-ad-preview').innerText(),/تقرير هندسي، فحص تربة/);
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('trbhh-v2-ad-draft-v1'))?.form.details && Object.values(JSON.parse(localStorage.getItem('trbhh-v2-ad-draft-v1')).form.details).some(v=>Array.isArray(v)&&v.length===2));
 await page.reload();await page.getByLabel('تقرير هندسي',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('تقرير هندسي',{exact:true}).isChecked(),true);
 assert.ok(await page.locator('.category-field-grid').first().evaluate(el=>parseFloat(getComputedStyle(el).rowGap)<=14));
 await page.screenshot({path:output+'/compact-fields-desktop.png',fullPage:true});
 await page.goto(origin+'/');
 const dropdown=page.locator('.category-dropdown');assert.equal(await dropdown.getAttribute('open'),null);
 await dropdown.locator('summary').click();
 const link=dropdown.getByRole('link',{name:'أراضٍ',exact:true});
 assert.ok((await link.getAttribute('href')).includes('subcategory='));
 await dropdown.getByLabel('ابحث عن قسم').fill('كمبيوتر');
 assert.equal(await dropdown.getByRole('link',{name:'كمبيوتر ولابتوب',exact:true}).count(),1);
 await dropdown.getByLabel('ابحث عن قسم').fill('');
 await page.screenshot({path:output+'/category-dropdown-desktop.png',fullPage:false});
 await page.goto(origin+'/search/?category='+encodeURIComponent('منزل وأثاث')+'&subcategory='+encodeURIComponent('أثاث مكتبي'));
 await page.locator('.search-listings .listing-card').first().waitFor();
 assert.equal(await page.locator('.search-listings .listing-card').count(),1);
 assert.match(await page.locator('.search-listings').innerText(),/كرسي مكتب/);
 await page.goto(origin+'/classification/');
 await page.locator('tbody tr').first().waitFor();
 assert.equal(await page.locator('tbody tr').count(),8);
 assert.equal(await page.locator('tbody').getByText('تلقائي واضح',{exact:true}).count(),8);
 await page.evaluate(()=>{
  const base={intent:'offer',category:'',subcategory:'',title:'عرض غامض أول',description:'وصف محفوظ لا يتغير أثناء نقل الإعلان بين الأقسام',price:'800',city:'الرياض',condition:'مستعمل',images:['/images/sofa.jpg'],details:{oldValue:'محفوظ'},spec1:'',spec2:'',status:'active',createdAt:'2026-09-19T00:00:00.000Z'};
  localStorage.setItem('trbhh-v2-seller-ads-v1',JSON.stringify([{...base,id:'unknown-1'},{...base,id:'unknown-2',title:'عرض غامض ثان'}]));
 });
 await page.reload();
 await page.getByLabel('عرض الإعلانات',{exact:true}).selectOption('review');
 assert.equal(await page.locator('tbody tr').count(),2);
 await page.getByLabel('تحديد جميع الإعلانات الظاهرة').check();
 await page.getByLabel('القسم المستهدف').selectOption('عقارات');
 await page.getByLabel('الفرع المستهدف').selectOption('أراضٍ');
 await page.getByRole('button',{name:'تحويل المحدد (2)',exact:true}).click();
 await page.getByRole('button',{name:'تأكيد التحويل',exact:true}).click();
 await page.getByText(/تم تحويل 2 إعلان/).waitFor();
 assert.equal(await page.locator('tbody tr').count(),0);
 const raw=await page.evaluate(()=>JSON.parse(localStorage.getItem('trbhh-v2-seller-ads-v1')));
 assert.equal(raw[0].category,'');assert.equal(raw[0].details.oldValue,'محفوظ');assert.deepEqual(raw[0].images,['/images/sofa.jpg']);
 await page.getByRole('button',{name:'تراجع عن آخر دفعة',exact:true}).click();
 assert.equal(await page.locator('tbody tr').count(),2);
 await page.getByLabel('عرض الإعلانات',{exact:true}).selectOption('all');
 const first=page.locator('[data-ad-key="market:101"]');
 await first.getByRole('button',{name:'تعديل القسم',exact:true}).click();
 await page.getByLabel('القسم المستهدف').selectOption('أخرى');
 await page.getByLabel('الفرع المستهدف').selectOption('أخرى');
 await page.getByRole('button',{name:'تحويل المحدد (1)',exact:true}).click();
 await page.getByRole('button',{name:'تأكيد التحويل',exact:true}).click();
 await page.getByText(/تم تحويل 1 إعلان/).waitFor();
 await page.goto(origin+'/ads/101/');
 assert.equal(await page.locator('.buyer-breadcrumbs').getByRole('link',{name:'أخرى',exact:true}).count(),1);
 await page.goto(origin+'/search/?category='+encodeURIComponent('أخرى')+'&subcategory='+encodeURIComponent('أخرى'));
 assert.equal(await page.locator('.search-listings .listing-card').count(),1);
 for(const path of ['/','/classification/','/field-settings/','/ads/new/']){
  await page.setViewportSize({width:390,height:844});await page.goto(origin+path);
  if(path==='/')await page.locator('.category-dropdown summary').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile overflow '+path);
  await page.screenshot({path:output+'/mobile-'+path.replaceAll('/','_')+'.png',fullPage:true});
 }
 assert.deepEqual(errors,[]);
 console.log('PASS: multi-choice options, required validation, persistence, compact spacing, dropdown, branch search, 8 clear classifications, bulk review queue, non-destructive reassignment, undo, public display and mobile.');
}finally{await browser.close();}
