import {beforeEach,describe,expect,it,vi} from 'vitest';
const state=vi.hoisted(()=>({query:vi.fn(),ready:vi.fn()}));
vi.mock('@/lib/prisma',()=>({prisma:{$queryRaw:state.query}}));
vi.mock('@/lib/commerce/schema',()=>({assertCommerceSchemaReady:state.ready}));
import {readPublicCommerceProduct} from '@/lib/commerce/public-product';
const row={id:20n,title:'<b>مطرقة اختبار</b>',price_minor:1000,stock_available:10,stock_reserved:1,images:['http://unsafe.test/x.webp','https://images.example/a.webp','/media/b.webp'],description:'<script>bad()</script> وصف صحيح',brand:'علامة',options:[{name:'اللون'}],variants:[{externalId:'variant-4',name:'أسود / XL / 220V / EU',sku:'CJ-XL-BLK',publicPriceMinor:1200,quantity:5,available:true,image:'https://images.example/black-xl.webp',options:{Color:'Black',Size:'XL',Voltage:'220V',Plug:'EU',Material:'Steel'}}],available:1,quantity:8,featured:1,source_id:8n,cj_source_id:null,cj_availability_json:null,cj_details_json:null};
describe('public commerce product filtering',()=>{
 beforeEach(()=>{vi.resetAllMocks();state.ready.mockResolvedValue(undefined);state.query.mockResolvedValue([row]);});
 it('returns only sanitized customer-facing product data and available variants',async()=>{const product=await readPublicCommerceProduct(20n);expect(product).toMatchObject({id:'20',title:'مطرقة اختبار',priceMinor:1000,stock:5,images:['https://images.example/a.webp','/media/b.webp'],description:'وصف صحيح',brand:'علامة',requiresVariantSelection:true,variants:[{key:'variant-4',name:'أسود / XL / 220V / EU',priceMinor:1200,stock:5}]});expect(JSON.stringify(product)).not.toMatch(/supplier|cost|margin|external_id|commerce_product/i);});
 it('retains every real provider option, SKU, and variant image dynamically without inventing a VID',async()=>{const product=await readPublicCommerceProduct(20n);expect(product?.variants[0]).toMatchObject({key:'variant-4',vid:null,sku:'CJ-XL-BLK',image:'https://images.example/black-xl.webp',attributes:{Color:'Black',Size:'XL',Voltage:'220V',Plug:'EU',Material:'Steel'}});expect(JSON.stringify(product)).not.toMatch(/supplier|cost|margin|external_id|commerce_product/i);});
 it('hides products with options when no verified available variant exists',async()=>{state.query.mockResolvedValue([{...row,variants:'[]'}]);await expect(readPublicCommerceProduct(20n)).resolves.toBeNull();});
 it('scenario 5: product with no stock is excluded, and invalid identifiers are rejected',async()=>{state.query.mockResolvedValue([{...row,source_id:null,options:'[]',variants:'[]',stock_available:0}]);await expect(readPublicCommerceProduct(20n)).resolves.toBeNull();await expect(readPublicCommerceProduct(0n)).resolves.toBeNull();});
 it('hides a CJ-linked commerce product without a valid Saudi stock and freight proof',async()=>{state.query.mockResolvedValue([{...row,cj_source_id:5n,cj_availability_json:null}]);await expect(readPublicCommerceProduct(20n)).resolves.toBeNull();});
 it('scenario 6: product with stock but no Saudi shipping quote is excluded',async()=>{state.query.mockResolvedValue([{...row,cj_source_id:5n,cj_availability_json:JSON.stringify({checkedAt:new Date().toISOString(),stockQuantity:7,shippingOptions:[]})}]);await expect(readPublicCommerceProduct(20n)).resolves.toBeNull();});
 it('returns a CJ-linked product only with a fresh valid stock and shipping proof without exposing the carrier name',async()=>{state.query.mockResolvedValue([{...row,cj_source_id:5n,cj_availability_json:JSON.stringify({checkedAt:new Date().toISOString(),stockQuantity:7,shippingOptions:[{name:'CJ Packet',priceUsd:4.2,deliveryDays:'8-15 days',originCountry:'CN'}]}),cj_details_json:JSON.stringify({weightMin:350,weightMax:420})}]);const product=await readPublicCommerceProduct(20n);expect(product).toMatchObject({saudiShippingAvailable:true,deliveryEstimate:'من 8 إلى 15 يوم',weightLabel:'350–420 غ'});expect(JSON.stringify(product)).not.toContain('CJ Packet');});
 it('builds CJ variants by VID and verified per-VID stock with all raw option keys',async()=>{state.query.mockResolvedValue([{...row,cj_source_id:5n,cj_availability_json:JSON.stringify({checkedAt:new Date().toISOString(),stockQuantity:2,variants:[{vid:'VID-1',stockQuantity:2}],shippingOptions:[{name:'Carrier',priceUsd:4,deliveryDays:'8-10 days',originCountry:'CN'}]}),cj_details_json:JSON.stringify({variants:[{vid:'VID-1',name:'Black XL',sku:'CJ-SKU-1',optionKey:'Color:Black; Size:XL; Voltage:220V; Plug:EU',attributes:{variantWeight:1200,length:30,width:20,height:10,variantImage:'https://images.example/black.webp',variantSellPrice:9.4}}]})}]);const product=await readPublicCommerceProduct(20n);expect(product?.variants).toHaveLength(1);expect(product?.variants[0]).toMatchObject({key:'VID-1',vid:'VID-1',sku:'CJ-SKU-1',image:'https://images.example/black.webp',attributes:{Color:'Black',Size:'XL',Voltage:'220V',Plug:'EU',variantWeight:'1200',length:'30',width:'20',height:'10'},priceMinor:1000,stock:2});});
});
