'use client';
import Link from 'next/link';
import {useState,type FormEvent} from 'react';
import {ArrowLeft,ArrowUpLeft,Armchair,BriefcaseBusiness,Building2,Car,Check,ChevronDown,Factory,MapPin,MessageCircle,Search,ShieldCheck,Smartphone,Sparkles,Store,Truck,Wheat,Wrench,Ellipsis,Plus,SlidersHorizontal} from 'lucide-react';
import {categories,cities,listings,stores,wanted} from '@/lib/demo-data';
import {ListingCard,Modal,SectionHeading} from '@/components/ui';
import {CategoryDropdown} from '@/components/category-dropdown';
import {useMarketListings} from '@/lib/classification-store';
const icons=[Building2,Car,Truck,Wheat,Smartphone,Armchair,Wrench,Factory,BriefcaseBusiness,Ellipsis];
export default function HomePage(){const listings=useMarketListings();const[q,setQ]=useState('');const[city,setCity]=useState('كل المدن');const[request,setRequest]=useState<(typeof wanted)[number]|null>(null);
 return <><section className="hero"><div className="container"><div className="hero-top"><div className="hero-copy"><span className="eyebrow"><span className="small-rule"/>سوقك. فرصتك. تربح.</span><h1>بيع. اشترِ. <em>وتربح.</em></h1><p>اعرض اللي عندك، واكتشف اللي تحتاجه،<br className="desktop-only"/> وتواصل مباشرة.</p><div className="hero-notes"><span><Check size={15}/> بدون عمولة</span><span><Check size={15}/> تواصل مباشر</span><span><Check size={15}/> في كل مدن المملكة</span></div></div><div className="hero-art" aria-hidden="true"><div className="hero-photo hero-photo-one"><img src="/images/sofa.jpg" alt=""/><span>لبيتك الجديد</span></div><div className="hero-photo hero-photo-two"><img src="/images/suv.jpg" alt=""/><span>لمشوارك الجاي</span></div><div className="hero-stamp"><img src="/logo.jpg" alt=""/><span>كل فرصة<br/><strong>لها تربح</strong></span></div></div></div><form className="hero-search" action="/search/"><div className="search-keyword"><Search size={24}/><input name="q" value={q} onChange={e=>setQ(e.target.value)} aria-label="وش تدور عليه؟" placeholder="وش تدور عليه اليوم؟"/></div><div className="search-city"><MapPin size={19}/><select name="city" aria-label="المدينة" value={city} onChange={e=>setCity(e.target.value)}>{cities.map(c=><option key={c}>{c}</option>)}</select></div><button className="button primary" type="submit">تصفح السوق<ArrowLeft size={18}/></button></form><div className="popular-searches"><span>عمليات بحث شائعة:</span>{['سيارات','عقارات','إلكترونيات','منزل وأثاث'].map(c=><Link key={c} href={`/search/?category=${encodeURIComponent(c)}`}>{c}</Link>)}</div></div></section>
 <div className="container"><section className="category-section"><SectionHeading title="وش يهمك؟" subtitle="كل اللي تحتاجه، في مكان واحد"/><CategoryDropdown/></section>
 <section className="section"><SectionHeading title="وصل السوق توّه" subtitle="اكتشف أحدث الإعلانات بالقرب منك" href="/search/" linkText="كل الإعلانات"/><div className="listing-grid">{listings.slice(0,8).map(l=><ListingCard listing={l} key={l.id}/>)}</div></section>
 <section className="section featured-section"><SectionHeading title="إعلانات مميزة" subtitle="ظهور مدفوع من أصحاب الإعلانات" href="/search/?featured=1"/><div className="listing-grid featured-grid">{listings.filter(l=>l.featured).map(l=><ListingCard key={l.id} listing={l}/>)}</div></section>
 <section className="section wanted-section"><SectionHeading title="مطلوب الآن" subtitle="يمكن اللي عندك، هو اللي يدور عليه غيرك" href="/search/?intent=wanted" linkText="شوف كل الطلبات"/><div className="wanted-grid">{wanted.map(w=><button className="wanted-card" key={w.id} onClick={()=>setRequest(w)}><div className="wanted-card-top"><span className="badge wanted-badge">مطلوب</span><span>{w.time}</span></div><h3>{w.title}</h3><p><MapPin size={14}/>{w.city}<span>·</span>{w.category}</p><div><b>{w.budget}</b><ArrowUpLeft size={21}/></div></button>)}</div></section>
 <section className="section" id="stores"><SectionHeading title="متاجر تستاهل تكتشفها" subtitle="أصحاب أنشطة، ومنتجات تستحق نظرة" href="/#stores" linkText="استكشف المتاجر"/><div className="store-grid">{stores.map((s,i)=><Link href={`/store/${['dar','tech','equipment'][i]}/`} className="store-card" key={s.name}><div className="store-initial" style={{background:s.color}}>{s.initial}</div><div><h3>{s.name}<ShieldCheck size={17}/></h3><p>{s.category}</p><span><MapPin size={13}/>{s.city}</span></div><ArrowLeft size={20}/></Link>)}</div></section>
 <section className="merchant-cta"><div className="merchant-icon"><Store size={46} strokeWidth={1.2}/></div><div><span className="eyebrow">لكل نشاط طموح</span><h2>متجرك يستحق مساحة أكبر.</h2><p>واجهة احترافية لنشاطك، إعلانات منظمة، وعملاء يتواصلون معك مباشرة.</p></div><Link className="button gold" href="/seller/">اكتشف تجربة المتجر<ArrowLeft size={18}/></Link></section>
 <section className="section trust-section" id="trust"><ShieldCheck size={32}/><div><h2>تربح يجمعكم. والوعي يحميكم.</h2><p>افحص السلعة قبل الدفع، وتحقق من الطرف الآخر، ولا تشارك رمز التحقق مع أحد.</p></div><span className="trust-label">تواصل مباشر · بدون عمولة</span></section></div>
 <Modal open={!!request} onClose={()=>setRequest(null)} title="تفاصيل المطلوب">{request&&<div className="request-detail"><span className="badge wanted-badge">مطلوب · مثال تجريبي</span><h3>{request.title}</h3><p>{request.detail}</p><p><MapPin size={16}/>{request.city} — {request.budget}</p><Link href="/messages/" className="button primary">مراسلة صاحب الطلب<MessageCircle size={17}/></Link></div>}</Modal></>
}
