'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState,type ReactNode} from 'react';
import {Bell,Heart,Home,MapPin,Menu,MessageCircle,Plus,Search,ShieldCheck,Store,UserRound,X} from 'lucide-react';
import {Modal} from './ui';
export function AppShell({children}:{children:ReactNode}){
 const path=usePathname();const[toast,setToast]=useState('');const[menu,setMenu]=useState(false);
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const fn=(e:Event)=>{setToast((e as CustomEvent<string>).detail);clearTimeout(timer);timer=setTimeout(()=>setToast(''),4200)};window.addEventListener('trbhh-notice',fn);return()=>{clearTimeout(timer);window.removeEventListener('trbhh-notice',fn)}},[]);
 const nav=[{href:'/',label:'الرئيسية',icon:Home},{href:'/search/',label:'البحث',icon:Search},{href:'/ads/new/',label:'أعلن',icon:Plus},{href:'/messages/',label:'الرسائل',icon:MessageCircle},{href:'/account/',label:'حسابي',icon:UserRound}];
 return <><a className="skip-link" href="#main">انتقل إلى المحتوى</a><div className="preview-strip"><span>TRBHH V2</span> معاينة التصميم · بيانات تجريبية <span className="strip-end">بدون تغيير الموقع الحالي</span></div><header className="site-header"><div className="container header-inner"><Link href="/" className="brand" aria-label="تربح الرئيسية"><img src="/logo.jpg" alt="تربح" width="54" height="54"/></Link><nav className="desktop-nav" aria-label="التنقل الرئيسي"><Link className={path==='/'?'active':''} href="/">السوق</Link><Link href="/search/?intent=wanted">مطلوب الآن</Link><Link href="/#stores">متاجر تربح</Link></nav><div className="header-actions"><Link href="/search/" className="header-city"><MapPin size={16}/> كل المدن</Link><Link className="icon-button desktop-only" href="/account/?tab=favorites" aria-label="المفضلة"><Heart size={20}/></Link><Link className="icon-button desktop-only" href="/messages/" aria-label="الرسائل"><MessageCircle size={20}/></Link><Link className="account-link desktop-only" href="/account/"><UserRound size={18}/> حسابي</Link><Link className="button primary header-post" href="/ads/new/"><Plus size={18}/> أضف إعلانك</Link><button className="icon-button mobile-menu" onClick={()=>setMenu(true)} aria-label="فتح القائمة"><Menu/></button></div></div></header><main id="main">{children}</main><footer className="site-footer"><div className="container footer-grid"><div><Link href="/" className="footer-brand">تربح<span>TRBHH</span></Link><p>سوق يجمعك باللي تحتاجه.<br/>بيع واشترِ وتواصل مباشرة، بدون عمولة.</p></div><div><b>اكتشف تربح</b><Link href="/search/">تصفح السوق</Link><Link href="/search/?intent=wanted">مطلوب الآن</Link><Link href="/#stores">متاجر تربح</Link></div><div><b>مساحتك</b><Link href="/seller/">لوحة البائع</Link><Link href="/account/credit/">رصيد تربح</Link><Link href="/account/">حسابي</Link></div><div className="footer-safety"><ShieldCheck size={25}/><b>تواصل بوعي، وتعامل بأمان</b><p>افحص السلعة وتأكد من الطرف الآخر قبل الدفع. تربح لا يستلم قيمة السلعة ولا يضمن الصفقة.</p></div></div><div className="container footer-bottom"><span>© تربح 2026</span><span>تصميم V2 للمراجعة · جميع العروض والأسماء أمثلة</span></div></footer>{!path.startsWith('/ads/')&&<nav className="bottom-nav" aria-label="تنقل الجوال">{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} className={`${path===href||path===href.slice(0,-1)?'active':''} ${label==='أعلن'?'post-tab':''}`}><span><Icon size={21}/></span>{label}</Link>)}</nav>}<div className={`toast ${toast?'show':''}`} role="status" aria-live="polite">{toast}</div><Modal title="تصفح تربح" open={menu} onClose={()=>setMenu(false)}><div className="mobile-menu-links">{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} onClick={()=>setMenu(false)}><Icon size={21}/>{label}</Link>)}<Link href="/#stores" onClick={()=>setMenu(false)}><Store size={21}/>متاجر تربح</Link></div></Modal></>
}
