'use client';
import Link from 'next/link';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowLeft,Check,Heart,MapPin,ShieldCheck,X} from 'lucide-react';
import {money,type Listing} from '@/lib/demo-data';
import {notify,readLocal,writeLocal} from '@/lib/preview';

export function Price({value}:{value:number}){return <span className="price"><bdi>{money(value)}</bdi><small>ر.س</small></span>}
export function FavoriteButton({id}:{id:string}){
 const [saved,setSaved]=useState(false);
 useEffect(()=>{const sync=()=>setSaved(readLocal<string[]>('favorites',[]).includes(id));sync();window.addEventListener('trbhh-favorites',sync);return()=>window.removeEventListener('trbhh-favorites',sync)},[id]);
 return <button className={`favorite-button ${saved?'is-saved':''}`} aria-label={saved?'إزالة من المفضلة':'حفظ في المفضلة'} aria-pressed={saved} onClick={e=>{e.preventDefault();e.stopPropagation();const all=readLocal<string[]>('favorites',[]);writeLocal('favorites',saved?all.filter(x=>x!==id):[...all,id]);window.dispatchEvent(new Event('trbhh-favorites'));notify(saved?'أُزيل الإعلان من المفضلة':'حُفظ الإعلان في مفضلتك التجريبية');}}><Heart size={19} fill={saved?'currentColor':'none'}/></button>
}
export function ListingCard({listing}:{listing:Listing}){return <article className="listing-card"><div className="listing-photo"><Link href={`/ads/${listing.id}/`} aria-label={listing.title}><img src={listing.image} alt={listing.title} loading="lazy" width="640" height="460"/></Link>{listing.featured&&<span className="featured-label">إعلان مميز</span>}<FavoriteButton id={listing.id}/></div><Link className="listing-body" href={`/ads/${listing.id}/`}><Price value={listing.price}/><h3>{listing.title}</h3><div className="listing-meta"><span><MapPin size={13}/>{listing.city}</span><span>{listing.time}</span></div><div className="listing-bottom"><span className="condition">{listing.condition}</span><span className="seller-name">{listing.verified&&<ShieldCheck size={14}/>} {listing.seller}</span></div></Link></article>}
export function SectionHeading({title,subtitle,href,linkText='عرض الكل'}:{title:string;subtitle?:string;href?:string;linkText?:string}){return <div className="section-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{href&&<Link href={href}>{linkText}<ArrowLeft size={17}/></Link>}</div>}
export function Modal({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){
 const ref=useRef<HTMLDivElement>(null);const closeRef=useRef(onClose);closeRef.current=onClose;
 useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector<HTMLButtonElement>('button')?.focus();const listener=(e:KeyboardEvent)=>{if(e.key==='Escape')closeRef.current();if(e.key==='Tab'){const items=ref.current?.querySelectorAll<HTMLElement>('button,a[href],input,select,textarea,[tabindex="0"]');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}};window.addEventListener('keydown',listener);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',listener);previous?.focus()}},[open]);
 if(!open)return null;return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal" role="dialog" aria-modal="true" aria-label={title} ref={ref}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="إغلاق" onClick={onClose}><X/></button></div>{children}</div></div>
}
export function PreviewAction({children,title='معاينة التواصل',className='button secondary'}:{children:ReactNode;title?:string;className?:string}){const[open,setOpen]=useState(false);return <><button type="button" className={className} onClick={()=>setOpen(true)}>{children}</button><Modal title={title} open={open} onClose={()=>setOpen(false)}><div className="modal-message"><span className="round-icon"><Check/></span><h3>هنا يبدأ التواصل المباشر</h3><p>في النسخة الفعلية ستستخدم الوسيلة التي أتاحها صاحب الإعلان. هذه معاينة ببيانات تجريبية؛ لا تُرسل رسائل ولا تتصل بأشخاص حقيقيين.</p><Link href="/messages/" className="button primary" onClick={()=>setOpen(false)}>جرّب واجهة الرسائل<ArrowLeft size={17}/></Link></div></Modal></>}
export function EmptyState({title,description}:{title:string;description:string}){return <div className="empty-state"><h3>{title}</h3><p>{description}</p><Link href="/ads/new/?intent=wanted" className="button secondary">انشر مطلوبًا</Link></div>}
